import {
  FLEET_EQUIPMENT_DETAIL_TAB_IMPORTS,
  FLEET_EQUIPMENT_DETAIL_TAB_STYLE_URLS,
} from '../fleet-equipment-detail-tab.shared';

export const FLEET_EQUIPMENT_COB_SECTION_IMPORTS = [...FLEET_EQUIPMENT_DETAIL_TAB_IMPORTS] as const;
export const FLEET_EQUIPMENT_COB_SECTION_STYLE_URLS = [
  ...FLEET_EQUIPMENT_DETAIL_TAB_STYLE_URLS,
] as const;
