import {
  FLEET_DETAIL_DRAWER_TAB_IMPORTS,
  FLEET_DETAIL_DRAWER_TAB_STYLES_DEPTH_2,
} from '@features/fleet/components/fleet-detail-drawer.shared';

export const FLEET_UNIT_COB_SECTION_IMPORTS = [...FLEET_DETAIL_DRAWER_TAB_IMPORTS] as const;
export const FLEET_UNIT_COB_SECTION_STYLE_URLS = FLEET_DETAIL_DRAWER_TAB_STYLES_DEPTH_2;
