import {
  FLEET_DETAIL_DRAWER_TAB_IMPORTS,
  FLEET_DETAIL_DRAWER_TAB_STYLES_DEPTH_2,
  FLEET_DETAIL_DRAWER_SHELL_STYLES,
} from '../fleet-detail-drawer.shared';

export {
  FLEET_DETAIL_DRAWER_TAB_IMPORTS,
  FLEET_DETAIL_DRAWER_TAB_STYLES_DEPTH_2,
  FLEET_DETAIL_DRAWER_SHELL_STYLES,
};

/** @deprecated Usar `FLEET_DETAIL_DRAWER_TAB_IMPORTS`. */
export { FLEET_DETAIL_DRAWER_TAB_IMPORTS as FLEET_UNIT_DETAIL_TAB_IMPORTS };

/** @deprecated Usar `FLEET_DETAIL_DRAWER_TAB_STYLES_DEPTH_2`. */
export const FLEET_UNIT_DETAIL_TAB_STYLE_URLS = FLEET_DETAIL_DRAWER_TAB_STYLES_DEPTH_2;
