import { Trip } from '@shared/models/logistics.models';

export const MOCK_TRIPS: Trip[] = [
  {
    id: 'FL-24102',
    maneuverCode: 'FL-24102',
    origin: 'Monterrey',
    destination: 'Guadalajara',
    clientName: 'FEMSA Logística',
    unitId: 'TRK-882',
    operatorId: 'op1',
    status: 'in_transit',
    programmedAt: '2026-05-09T20:15:00Z',
    scheduledAt: '2026-05-10T08:00:00Z',
    operationType: 'full',
    loadType: 'lleno',
    containerType: '40ft',
    approximateWeightTons: '23',
    equipment: ['Thermo TK-12', 'Semirremolque SR-04'],
    departureAt: '2026-05-10T07:58:00Z',
    arrivedAt: null,
    returnAt: null,
    creditDays: 45,
    hasIncident: false,
    incidents: [],
    routeDistanceKm: 718.2,
    maneuverKind: 'Foránea',
    dieselLiters: '820',
    dieselAmount: '18450',
    casetasAmount: '3850',
    operatorQuota: '2800',
    clientCharge: '58500',
    paymentMethod: 'transfer',
    requiresInvoice: true,
    hasClientBilling: true,
    attachedDocumentFileNames: [
      'Carta-porte-FL-24102.pdf',
      'BOL-escaneo.jpg',
      'Seguro-carga.pdf',
    ],
  },
  {
    id: 'LV-24101',
    maneuverCode: 'LV-24101',
    origin: 'CDMX',
    destination: 'Querétaro',
    clientName: 'Liverpool',
    unitId: 'TRK-441',
    operatorId: 'op2',
    status: 'scheduled',
    programmedAt: '2026-05-09T18:40:00Z',
    scheduledAt: '2026-05-11T14:30:00Z',
    operationType: 'sencillo',
    loadType: 'vacio',
    containerType: 'na',
    approximateWeightTons: '',
    equipment: ['Caja seca CS-01'],
    departureAt: null,
    arrivedAt: null,
    returnAt: null,
    creditDays: 30,
    hasIncident: false,
    incidents: [],
    routeDistanceKm: 218.7,
    maneuverKind: 'Foránea',
    dieselLiters: '285',
    dieselAmount: '6410',
    casetasAmount: '1240',
    operatorQuota: '1500',
    clientCharge: '22400',
    paymentMethod: 'transfer',
    requiresInvoice: true,
    hasClientBilling: true,
    attachedDocumentFileNames: ['Programacion-LV-24101.pdf', 'Check-list-vacio.docx'],
  },
  {
    id: 'OS-24100',
    maneuverCode: 'OS-24100',
    origin: 'Tijuana',
    destination: 'Mexicali',
    clientName: 'Organización Soriana',
    unitId: 'TRK-204',
    operatorId: 'op3',
    status: 'in_transit',
    programmedAt: '2026-05-09T17:05:00Z',
    scheduledAt: '2026-05-09T22:00:00Z',
    operationType: 'plana',
    loadType: 'lleno',
    containerType: 'na',
    approximateWeightTons: '14',
    equipment: ['Plana extendida PL-09'],
    departureAt: '2026-05-09T21:45:00Z',
    arrivedAt: null,
    returnAt: null,
    creditDays: 15,
    hasIncident: true,
    incidents: [
      {
        id: 'inc-os-demo-1',
        description: 'Retraso en caseta por revisión aleatoria.',
        occurredAt: '2026-05-09T22:08:00Z',
      },
    ],
    routeDistanceKm: 182.4,
    maneuverKind: 'Foránea',
    dieselLiters: '195',
    dieselAmount: '4385',
    casetasAmount: '890',
    operatorQuota: '1200',
    clientCharge: '18950',
    paymentMethod: 'cash',
    requiresInvoice: false,
    hasClientBilling: true,
    attachedDocumentFileNames: ['Remision-OS-24100.pdf'],
  },
  {
    id: 'IB-24099',
    maneuverCode: 'IB-24099',
    origin: 'León',
    destination: 'Aguascalientes',
    clientName: 'Industrias Bachoco',
    unitId: 'TRK-118',
    operatorId: 'op1',
    status: 'completed',
    programmedAt: '2026-05-09T15:20:00Z',
    scheduledAt: '2026-05-09T16:45:00Z',
    operationType: 'sencillo',
    loadType: 'vacio',
    containerType: '40hc',
    approximateWeightTons: '',
    equipment: ['Dry van DV-22'],
    departureAt: '2026-05-09T16:40:00Z',
    arrivedAt: '2026-05-09T19:10:00Z',
    returnAt: '2026-05-09T21:30:00Z',
    creditDays: 30,
    hasIncident: false,
    incidents: [],
    routeDistanceKm: 125.9,
    maneuverKind: 'Foránea',
    dieselLiters: '168',
    dieselAmount: '3775',
    casetasAmount: '510',
    operatorQuota: '950',
    clientCharge: '14200',
    paymentMethod: 'check',
    requiresInvoice: true,
    hasClientBilling: true,
    attachedDocumentFileNames: [
      'Carta-porte-IB-24099.pdf',
      'Foto-carga-terminal.png',
      'POD-firma.jpeg',
    ],
  },
  {
    id: 'KC-24098',
    maneuverCode: 'KC-24098',
    origin: 'Puebla',
    destination: 'Veracruz',
    clientName: 'Kimberly-Clark',
    unitId: 'TRK-909',
    operatorId: 'op4',
    status: 'in_transit',
    programmedAt: '2026-05-09T12:30:00Z',
    scheduledAt: '2026-05-09T12:00:00Z',
    operationType: 'full',
    loadType: 'lleno',
    containerType: '40hc',
    approximateWeightTons: '18,5',
    equipment: ['Refrigerado RF-03', 'Semirremolque SR-11'],
    departureAt: '2026-05-09T11:55:00Z',
    arrivedAt: null,
    returnAt: null,
    creditDays: 60,
    hasIncident: false,
    incidents: [],
    routeDistanceKm: 297.6,
    maneuverKind: 'Foránea',
    dieselLiters: '442',
    dieselAmount: '9945',
    casetasAmount: '2180',
    operatorQuota: '2100',
    clientCharge: '48200',
    paymentMethod: 'transfer',
    requiresInvoice: true,
    hasClientBilling: true,
    attachedDocumentFileNames: ['Temperatura-cadena-frio.pdf', 'Manifiesto-KC-24098.pdf'],
  },
  {
    id: 'GM-24097',
    maneuverCode: 'GM-24097',
    origin: 'Mérida',
    destination: 'Cancún',
    clientName: 'Grupo Modelo',
    unitId: 'TRK-330',
    operatorId: 'op2',
    status: 'scheduled',
    programmedAt: '2026-05-09T10:00:00Z',
    scheduledAt: '2026-05-12T06:00:00Z',
    operationType: 'full',
    loadType: 'vacio',
    containerType: '40ft',
    approximateWeightTons: '',
    equipment: ['Thermo TK-08', 'Caja alta CA-02'],
    departureAt: null,
    arrivedAt: null,
    returnAt: null,
    creditDays: 45,
    hasIncident: false,
    incidents: [],
    routeDistanceKm: 320.8,
    maneuverKind: 'Foránea',
    dieselLiters: '378',
    dieselAmount: '8505',
    casetasAmount: '1655',
    operatorQuota: '1750',
    clientCharge: '35600',
    paymentMethod: 'transfer',
    requiresInvoice: false,
    hasClientBilling: true,
    attachedDocumentFileNames: ['Booking-GM-24097.pdf'],
  },
  {
    id: 'PE-24096',
    maneuverCode: 'PE-24096',
    origin: 'Saltillo',
    destination: 'Torreón',
    clientName: 'Peñoles',
    unitId: 'TRK-501',
    operatorId: 'op5',
    status: 'completed',
    programmedAt: '2026-05-08T22:00:00Z',
    scheduledAt: '2026-05-08T19:30:00Z',
    operationType: 'plana',
    loadType: 'lleno',
    containerType: '20ft',
    approximateWeightTons: '8',
    equipment: ['Plana PL-07'],
    departureAt: '2026-05-08T19:25:00Z',
    arrivedAt: '2026-05-08T21:50:00Z',
    returnAt: '2026-05-09T01:15:00Z',
    creditDays: 21,
    hasIncident: false,
    incidents: [],
    routeDistanceKm: 279.5,
    maneuverKind: 'Foránea',
    dieselLiters: '255',
    dieselAmount: '5738',
    casetasAmount: '995',
    operatorQuota: '1100',
    clientCharge: '19875',
    paymentMethod: 'cash',
    requiresInvoice: true,
    hasClientBilling: true,
    attachedDocumentFileNames: ['Ticket-casetas-PE.pdf', 'Entrega-PE-24096.pdf'],
  },
  {
    id: 'WM-24095',
    maneuverCode: 'WM-24095',
    origin: 'Chihuahua',
    destination: 'Hermosillo',
    clientName: 'Walmart de México',
    unitId: 'TRK-775',
    operatorId: 'op3',
    status: 'cancelled',
    programmedAt: '2026-05-08T16:45:00Z',
    scheduledAt: '2026-05-08T09:00:00Z',
    operationType: 'sencillo',
    loadType: 'vacio',
    containerType: 'na',
    approximateWeightTons: '',
    equipment: ['Góndola GD-05'],
    departureAt: null,
    arrivedAt: null,
    returnAt: null,
    creditDays: 90,
    hasIncident: false,
    incidents: [],
    routeDistanceKm: 1214.6,
    maneuverKind: 'Foránea',
    dieselLiters: '980',
    dieselAmount: '22050',
    casetasAmount: '5420',
    operatorQuota: '3200',
    clientCharge: '0',
    paymentMethod: 'cash',
    requiresInvoice: false,
    hasClientBilling: false,
    attachedDocumentFileNames: ['Memo-cancelacion.pdf'],
  },
  {
    id: 'SA-24094',
    maneuverCode: 'SA-24094',
    origin: 'Morelia',
    destination: 'Colima',
    clientName: 'Sigma Alimentos',
    unitId: 'TRK-612',
    operatorId: 'op1',
    status: 'completed',
    programmedAt: '2026-05-08T09:30:00Z',
    scheduledAt: '2026-05-07T21:15:00Z',
    operationType: 'full',
    loadType: 'lleno',
    containerType: '40ft',
    approximateWeightTons: '24',
    equipment: ['Thermo TK-01', 'Semirremolque SR-02'],
    departureAt: '2026-05-07T21:10:00Z',
    arrivedAt: '2026-05-08T02:40:00Z',
    returnAt: '2026-05-08T06:05:00Z',
    creditDays: 30,
    hasIncident: false,
    incidents: [],
    routeDistanceKm: 404.3,
    maneuverKind: 'Foránea',
    dieselLiters: '512',
    dieselAmount: '11520',
    casetasAmount: '2460',
    operatorQuota: '2650',
    clientCharge: '52800',
    paymentMethod: 'transfer',
    requiresInvoice: true,
    hasClientBilling: true,
    attachedDocumentFileNames: ['CP-SA-24094.pdf', 'Sellos-terminal.jpg', 'Temperatura-ruta.pdf'],
  },
  {
    id: 'CF-24093',
    maneuverCode: 'CF-24093',
    origin: 'Toluca',
    destination: 'Cuernavaca',
    clientName: 'Coca-Cola FEMSA',
    unitId: 'TRK-148',
    operatorId: 'op4',
    status: 'completed',
    programmedAt: '2026-05-07T19:00:00Z',
    scheduledAt: '2026-05-07T14:00:00Z',
    operationType: 'sencillo',
    loadType: 'lleno',
    containerType: '40hc',
    approximateWeightTons: '11,2',
    equipment: ['Torton TM-14'],
    departureAt: '2026-05-07T13:55:00Z',
    arrivedAt: '2026-05-07T15:20:00Z',
    returnAt: '2026-05-07T17:45:00Z',
    creditDays: 7,
    hasIncident: false,
    incidents: [],
    routeDistanceKm: 18.2,
    maneuverKind: 'Local',
    dieselLiters: '62',
    dieselAmount: '1395',
    casetasAmount: '0',
    operatorQuota: '650',
    clientCharge: '9850',
    paymentMethod: 'cash',
    requiresInvoice: false,
    hasClientBilling: true,
    attachedDocumentFileNames: ['Factura-CF-24093.xml', 'Evidencia-entrega.png'],
  },
];
