import { Equipment } from '@shared/models/logistics.models';

/** Dos remolques por tractor para poder armar servicios full. */
export const SIM_DB_EQUIPMENT: Equipment[] = [
  {
    id: "DEMO-TRC-001-EQ1",
    unitId: "DEMO-TRC-001",
    name: "",
    serialNumber: "EQ-SN-001-1",
    lastServiceDate: "2026-04-01",
    plate: "01-RM-1",
    type: "portacontenedor",
    status: "in_use",
    trailerBrandAbbr: "DEM",
    trailerYear: "2020",
    fleetMeta: {
      trailerBrandName: "Demo Trailers SA",
      trailerVersion: "portacontenedor",
      equipmentCapacityTons: "32",
      verificationPhysMechDate: "2025-09-18",
      verificationPhysMechCost: 1380,
      lastMaintenanceDate: "2026-03-22",
      lastMaintenanceType: "servicio_completo",
      lastMaintenanceCost: 9800,
      maintenanceEntries: [
        {
          date: "2026-03-22",
          type: "servicio_completo",
          cost: 9800,
          status: "concluido",
          notes: "48 puntos, luces y frenos.",
        },
        {
          date: "2025-10-05",
          type: "medio_servicio",
          cost: 5100,
          status: "concluido",
        },
      ],
      documentVerificationNames: ["verif-fisica-remolque.pdf"],
      insurancePolicyNumber: "EQ-POL-001-1",
      insuranceContractDate: "2025-06-01",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-001-EQ2",
    unitId: "DEMO-TRC-001",
    name: "",
    serialNumber: "EQ-SN-001-2",
    lastServiceDate: "2026-04-01",
    plate: "01-RM-2",
    type: "portacontenedor",
    status: "in_use",
    trailerBrandAbbr: "DEM",
    trailerYear: "2020",
    fleetMeta: {
      trailerBrandName: "Demo Trailers SA",
      trailerVersion: "portacontenedor",
      equipmentCapacityTons: "32",
      verificationPhysMechDate: "2025-09-18",
      verificationPhysMechCost: 1380,
      lastMaintenanceDate: "2026-03-22",
      lastMaintenanceType: "servicio_completo",
      lastMaintenanceCost: 9800,
      maintenanceEntries: [
        {
          date: "2026-03-22",
          type: "servicio_completo",
          cost: 9800,
          status: "concluido",
          notes: "48 puntos, luces y frenos.",
        },
        {
          date: "2025-10-05",
          type: "medio_servicio",
          cost: 5100,
          status: "concluido",
        },
      ],
      documentVerificationNames: ["verif-fisica-remolque.pdf"],
      insurancePolicyNumber: "EQ-POL-001-2",
      insuranceContractDate: "2025-06-01",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-002-EQ1",
    unitId: "DEMO-TRC-002",
    name: "",
    serialNumber: "EQ-SN-002-1",
    lastServiceDate: "2026-04-01",
    plate: "02-RM-1",
    type: "plataforma",
    status: "in_use",
    trailerBrandAbbr: "DEM",
    trailerYear: "2020",
    fleetMeta: {
      trailerBrandName: "Demo Trailers SA",
      trailerVersion: "plataforma",
      equipmentCapacityTons: "24",
      verificationPhysMechDate: "2025-09-18",
      verificationPhysMechCost: 1380,
      lastMaintenanceDate: "2026-03-22",
      lastMaintenanceType: "servicio_completo",
      lastMaintenanceCost: 9800,
      maintenanceEntries: [
        {
          date: "2026-03-22",
          type: "servicio_completo",
          cost: 9800,
          status: "concluido",
          notes: "48 puntos, luces y frenos.",
        },
        {
          date: "2025-10-05",
          type: "medio_servicio",
          cost: 5100,
          status: "concluido",
        },
      ],
      documentVerificationNames: ["verif-fisica-remolque.pdf"],
      insurancePolicyNumber: "EQ-POL-002-1",
      insuranceContractDate: "2025-06-01",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-002-EQ2",
    unitId: "DEMO-TRC-002",
    name: "",
    serialNumber: "EQ-SN-002-2",
    lastServiceDate: "2026-04-01",
    plate: "02-RM-2",
    type: "caja seca",
    status: "in_use",
    trailerBrandAbbr: "DEM",
    trailerYear: "2020",
    fleetMeta: {
      trailerBrandName: "Demo Trailers SA",
      trailerVersion: "caja seca",
      equipmentCapacityTons: "24",
      verificationPhysMechDate: "2025-09-18",
      verificationPhysMechCost: 1380,
      lastMaintenanceDate: "2026-03-22",
      lastMaintenanceType: "servicio_completo",
      lastMaintenanceCost: 9800,
      maintenanceEntries: [
        {
          date: "2026-03-22",
          type: "servicio_completo",
          cost: 9800,
          status: "concluido",
          notes: "48 puntos, luces y frenos.",
        },
        {
          date: "2025-10-05",
          type: "medio_servicio",
          cost: 5100,
          status: "concluido",
        },
      ],
      documentVerificationNames: ["verif-fisica-remolque.pdf"],
      insurancePolicyNumber: "EQ-POL-002-2",
      insuranceContractDate: "2025-06-01",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-003-EQ1",
    unitId: "DEMO-TRC-003",
    name: "",
    serialNumber: "EQ-SN-003-1",
    lastServiceDate: "2026-04-01",
    plate: "03-RM-1",
    type: "plataforma",
    status: "in_use",
    trailerBrandAbbr: "DEM",
    trailerYear: "2020",
    fleetMeta: {
      trailerBrandName: "Demo Trailers SA",
      trailerVersion: "plataforma",
      equipmentCapacityTons: "24",
      verificationPhysMechDate: "2025-09-18",
      verificationPhysMechCost: 1380,
      lastMaintenanceDate: "2026-03-22",
      lastMaintenanceType: "servicio_completo",
      lastMaintenanceCost: 9800,
      maintenanceEntries: [
        {
          date: "2026-03-22",
          type: "servicio_completo",
          cost: 9800,
          status: "concluido",
          notes: "48 puntos, luces y frenos.",
        },
        {
          date: "2025-10-05",
          type: "medio_servicio",
          cost: 5100,
          status: "concluido",
        },
      ],
      documentVerificationNames: ["verif-fisica-remolque.pdf"],
      insurancePolicyNumber: "EQ-POL-003-1",
      insuranceContractDate: "2025-06-01",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-003-EQ2",
    unitId: "DEMO-TRC-003",
    name: "",
    serialNumber: "EQ-SN-003-2",
    lastServiceDate: "2026-04-01",
    plate: "03-RM-2",
    type: "plataforma",
    status: "in_use",
    trailerBrandAbbr: "DEM",
    trailerYear: "2020",
    fleetMeta: {
      trailerBrandName: "Demo Trailers SA",
      trailerVersion: "plataforma",
      equipmentCapacityTons: "24",
      verificationPhysMechDate: "2025-09-18",
      verificationPhysMechCost: 1380,
      lastMaintenanceDate: "2026-03-22",
      lastMaintenanceType: "servicio_completo",
      lastMaintenanceCost: 9800,
      maintenanceEntries: [
        {
          date: "2026-03-22",
          type: "servicio_completo",
          cost: 9800,
          status: "concluido",
          notes: "48 puntos, luces y frenos.",
        },
        {
          date: "2025-10-05",
          type: "medio_servicio",
          cost: 5100,
          status: "concluido",
        },
      ],
      documentVerificationNames: ["verif-fisica-remolque.pdf"],
      insurancePolicyNumber: "EQ-POL-003-2",
      insuranceContractDate: "2025-06-01",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-004-EQ1",
    unitId: "DEMO-TRC-004",
    name: "",
    serialNumber: "EQ-SN-004-1",
    lastServiceDate: "2026-04-01",
    plate: "04-RM-1",
    type: "plataforma",
    status: "in_use",
    trailerBrandAbbr: "DEM",
    trailerYear: "2020",
    fleetMeta: {
      trailerBrandName: "Demo Trailers SA",
      trailerVersion: "plataforma",
      equipmentCapacityTons: "24",
      verificationPhysMechDate: "2025-09-18",
      verificationPhysMechCost: 1380,
      lastMaintenanceDate: "2026-03-22",
      lastMaintenanceType: "servicio_completo",
      lastMaintenanceCost: 9800,
      maintenanceEntries: [
        {
          date: "2026-03-22",
          type: "servicio_completo",
          cost: 9800,
          status: "concluido",
          notes: "48 puntos, luces y frenos.",
        },
        {
          date: "2025-10-05",
          type: "medio_servicio",
          cost: 5100,
          status: "concluido",
        },
      ],
      documentVerificationNames: ["verif-fisica-remolque.pdf"],
      insurancePolicyNumber: "EQ-POL-004-1",
      insuranceContractDate: "2025-06-01",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-004-EQ2",
    unitId: "DEMO-TRC-004",
    name: "",
    serialNumber: "EQ-SN-004-2",
    lastServiceDate: "2026-04-01",
    plate: "04-RM-2",
    type: "plataforma",
    status: "in_use",
    trailerBrandAbbr: "DEM",
    trailerYear: "2020",
    fleetMeta: {
      trailerBrandName: "Demo Trailers SA",
      trailerVersion: "plataforma",
      equipmentCapacityTons: "24",
      verificationPhysMechDate: "2025-09-18",
      verificationPhysMechCost: 1380,
      lastMaintenanceDate: "2026-03-22",
      lastMaintenanceType: "servicio_completo",
      lastMaintenanceCost: 9800,
      maintenanceEntries: [
        {
          date: "2026-03-22",
          type: "servicio_completo",
          cost: 9800,
          status: "concluido",
          notes: "48 puntos, luces y frenos.",
        },
        {
          date: "2025-10-05",
          type: "medio_servicio",
          cost: 5100,
          status: "concluido",
        },
      ],
      documentVerificationNames: ["verif-fisica-remolque.pdf"],
      insurancePolicyNumber: "EQ-POL-004-2",
      insuranceContractDate: "2025-06-01",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-005-EQ1",
    unitId: "DEMO-TRC-005",
    name: "",
    serialNumber: "EQ-SN-005-1",
    lastServiceDate: "2026-04-01",
    plate: "05-RM-1",
    type: "refrigerado",
    status: "in_use",
    trailerBrandAbbr: "DEM",
    trailerYear: "2020",
    fleetMeta: {
      trailerBrandName: "Demo Trailers SA",
      trailerVersion: "refrigerado",
      equipmentCapacityTons: "24",
      verificationPhysMechDate: "2025-09-18",
      verificationPhysMechCost: 1380,
      lastMaintenanceDate: "2026-03-22",
      lastMaintenanceType: "servicio_completo",
      lastMaintenanceCost: 9800,
      maintenanceEntries: [
        {
          date: "2026-03-22",
          type: "servicio_completo",
          cost: 9800,
          status: "concluido",
          notes: "48 puntos, luces y frenos.",
        },
        {
          date: "2025-10-05",
          type: "medio_servicio",
          cost: 5100,
          status: "concluido",
        },
      ],
      documentVerificationNames: ["verif-fisica-remolque.pdf"],
      insurancePolicyNumber: "EQ-POL-005-1",
      insuranceContractDate: "2025-06-01",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-005-EQ2",
    unitId: "DEMO-TRC-005",
    name: "",
    serialNumber: "EQ-SN-005-2",
    lastServiceDate: "2026-04-01",
    plate: "05-RM-2",
    type: "plataforma",
    status: "in_use",
    trailerBrandAbbr: "DEM",
    trailerYear: "2020",
    fleetMeta: {
      trailerBrandName: "Demo Trailers SA",
      trailerVersion: "plataforma",
      equipmentCapacityTons: "24",
      verificationPhysMechDate: "2025-09-18",
      verificationPhysMechCost: 1380,
      lastMaintenanceDate: "2026-03-22",
      lastMaintenanceType: "servicio_completo",
      lastMaintenanceCost: 9800,
      maintenanceEntries: [
        {
          date: "2026-03-22",
          type: "servicio_completo",
          cost: 9800,
          status: "concluido",
          notes: "48 puntos, luces y frenos.",
        },
        {
          date: "2025-10-05",
          type: "medio_servicio",
          cost: 5100,
          status: "concluido",
        },
      ],
      documentVerificationNames: ["verif-fisica-remolque.pdf"],
      insurancePolicyNumber: "EQ-POL-005-2",
      insuranceContractDate: "2025-06-01",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-006-EQ1",
    unitId: "DEMO-TRC-006",
    name: "",
    serialNumber: "EQ-SN-006-1",
    lastServiceDate: "2026-04-01",
    plate: "06-RM-1",
    type: "portacontenedor",
    status: "scheduled",
    trailerBrandAbbr: "DEM",
    trailerYear: "2020",
    fleetMeta: {
      trailerBrandName: "Demo Trailers SA",
      trailerVersion: "portacontenedor",
      equipmentCapacityTons: "32",
      verificationPhysMechDate: "2025-09-18",
      verificationPhysMechCost: 1380,
      lastMaintenanceDate: "2026-03-22",
      lastMaintenanceType: "servicio_completo",
      lastMaintenanceCost: 9800,
      maintenanceEntries: [
        {
          date: "2026-03-22",
          type: "servicio_completo",
          cost: 9800,
          status: "concluido",
          notes: "48 puntos, luces y frenos.",
        },
        {
          date: "2025-10-05",
          type: "medio_servicio",
          cost: 5100,
          status: "concluido",
        },
      ],
      documentVerificationNames: ["verif-fisica-remolque.pdf"],
      insurancePolicyNumber: "EQ-POL-006-1",
      insuranceContractDate: "2025-06-01",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-006-EQ2",
    unitId: "DEMO-TRC-006",
    name: "",
    serialNumber: "EQ-SN-006-2",
    lastServiceDate: "2026-04-01",
    plate: "06-RM-2",
    type: "portacontenedor",
    status: "scheduled",
    trailerBrandAbbr: "DEM",
    trailerYear: "2020",
    fleetMeta: {
      trailerBrandName: "Demo Trailers SA",
      trailerVersion: "portacontenedor",
      equipmentCapacityTons: "32",
      verificationPhysMechDate: "2025-09-18",
      verificationPhysMechCost: 1380,
      lastMaintenanceDate: "2026-03-22",
      lastMaintenanceType: "servicio_completo",
      lastMaintenanceCost: 9800,
      maintenanceEntries: [
        {
          date: "2026-03-22",
          type: "servicio_completo",
          cost: 9800,
          status: "concluido",
          notes: "48 puntos, luces y frenos.",
        },
        {
          date: "2025-10-05",
          type: "medio_servicio",
          cost: 5100,
          status: "concluido",
        },
      ],
      documentVerificationNames: ["verif-fisica-remolque.pdf"],
      insurancePolicyNumber: "EQ-POL-006-2",
      insuranceContractDate: "2025-06-01",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-007-EQ1",
    unitId: "DEMO-TRC-007",
    name: "",
    serialNumber: "EQ-SN-007-1",
    lastServiceDate: "2026-04-01",
    plate: "07-RM-1",
    type: "caja seca",
    status: "scheduled",
    trailerBrandAbbr: "DEM",
    trailerYear: "2020",
    fleetMeta: {
      trailerBrandName: "Demo Trailers SA",
      trailerVersion: "caja seca",
      equipmentCapacityTons: "24",
      verificationPhysMechDate: "2025-09-18",
      verificationPhysMechCost: 1380,
      lastMaintenanceDate: "2026-03-22",
      lastMaintenanceType: "servicio_completo",
      lastMaintenanceCost: 9800,
      maintenanceEntries: [
        {
          date: "2026-03-22",
          type: "servicio_completo",
          cost: 9800,
          status: "concluido",
          notes: "48 puntos, luces y frenos.",
        },
        {
          date: "2025-10-05",
          type: "medio_servicio",
          cost: 5100,
          status: "concluido",
        },
      ],
      documentVerificationNames: ["verif-fisica-remolque.pdf"],
      insurancePolicyNumber: "EQ-POL-007-1",
      insuranceContractDate: "2025-06-01",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-007-EQ2",
    unitId: "DEMO-TRC-007",
    name: "",
    serialNumber: "EQ-SN-007-2",
    lastServiceDate: "2026-04-01",
    plate: "07-RM-2",
    type: "plataforma",
    status: "scheduled",
    trailerBrandAbbr: "DEM",
    trailerYear: "2020",
    fleetMeta: {
      trailerBrandName: "Demo Trailers SA",
      trailerVersion: "plataforma",
      equipmentCapacityTons: "24",
      verificationPhysMechDate: "2025-09-18",
      verificationPhysMechCost: 1380,
      lastMaintenanceDate: "2026-03-22",
      lastMaintenanceType: "servicio_completo",
      lastMaintenanceCost: 9800,
      maintenanceEntries: [
        {
          date: "2026-03-22",
          type: "servicio_completo",
          cost: 9800,
          status: "concluido",
          notes: "48 puntos, luces y frenos.",
        },
        {
          date: "2025-10-05",
          type: "medio_servicio",
          cost: 5100,
          status: "concluido",
        },
      ],
      documentVerificationNames: ["verif-fisica-remolque.pdf"],
      insurancePolicyNumber: "EQ-POL-007-2",
      insuranceContractDate: "2025-06-01",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-008-EQ1",
    unitId: "DEMO-TRC-008",
    name: "",
    serialNumber: "EQ-SN-008-1",
    lastServiceDate: "2026-04-01",
    plate: "08-RM-1",
    type: "plataforma",
    status: "scheduled",
    trailerBrandAbbr: "DEM",
    trailerYear: "2020",
    fleetMeta: {
      trailerBrandName: "Demo Trailers SA",
      trailerVersion: "plataforma",
      equipmentCapacityTons: "24",
      verificationPhysMechDate: "2025-09-18",
      verificationPhysMechCost: 1380,
      lastMaintenanceDate: "2026-03-22",
      lastMaintenanceType: "servicio_completo",
      lastMaintenanceCost: 9800,
      maintenanceEntries: [
        {
          date: "2026-03-22",
          type: "servicio_completo",
          cost: 9800,
          status: "concluido",
          notes: "48 puntos, luces y frenos.",
        },
        {
          date: "2025-10-05",
          type: "medio_servicio",
          cost: 5100,
          status: "concluido",
        },
      ],
      documentVerificationNames: ["verif-fisica-remolque.pdf"],
      insurancePolicyNumber: "EQ-POL-008-1",
      insuranceContractDate: "2025-06-01",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-008-EQ2",
    unitId: "DEMO-TRC-008",
    name: "",
    serialNumber: "EQ-SN-008-2",
    lastServiceDate: "2026-04-01",
    plate: "08-RM-2",
    type: "plataforma",
    status: "scheduled",
    trailerBrandAbbr: "DEM",
    trailerYear: "2020",
    fleetMeta: {
      trailerBrandName: "Demo Trailers SA",
      trailerVersion: "plataforma",
      equipmentCapacityTons: "24",
      verificationPhysMechDate: "2025-09-18",
      verificationPhysMechCost: 1380,
      lastMaintenanceDate: "2026-03-22",
      lastMaintenanceType: "servicio_completo",
      lastMaintenanceCost: 9800,
      maintenanceEntries: [
        {
          date: "2026-03-22",
          type: "servicio_completo",
          cost: 9800,
          status: "concluido",
          notes: "48 puntos, luces y frenos.",
        },
        {
          date: "2025-10-05",
          type: "medio_servicio",
          cost: 5100,
          status: "concluido",
        },
      ],
      documentVerificationNames: ["verif-fisica-remolque.pdf"],
      insurancePolicyNumber: "EQ-POL-008-2",
      insuranceContractDate: "2025-06-01",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-009-EQ1",
    unitId: "DEMO-TRC-009",
    name: "",
    serialNumber: "EQ-SN-009-1",
    lastServiceDate: "2026-04-01",
    plate: "09-RM-1",
    type: "portacontenedor",
    status: "scheduled",
    trailerBrandAbbr: "DEM",
    trailerYear: "2020",
    fleetMeta: {
      trailerBrandName: "Demo Trailers SA",
      trailerVersion: "portacontenedor",
      equipmentCapacityTons: "32",
      verificationPhysMechDate: "2025-09-18",
      verificationPhysMechCost: 1380,
      lastMaintenanceDate: "2026-03-22",
      lastMaintenanceType: "servicio_completo",
      lastMaintenanceCost: 9800,
      maintenanceEntries: [
        {
          date: "2026-03-22",
          type: "servicio_completo",
          cost: 9800,
          status: "concluido",
          notes: "48 puntos, luces y frenos.",
        },
        {
          date: "2025-10-05",
          type: "medio_servicio",
          cost: 5100,
          status: "concluido",
        },
      ],
      documentVerificationNames: ["verif-fisica-remolque.pdf"],
      insurancePolicyNumber: "EQ-POL-009-1",
      insuranceContractDate: "2025-06-01",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-009-EQ2",
    unitId: "DEMO-TRC-009",
    name: "",
    serialNumber: "EQ-SN-009-2",
    lastServiceDate: "2026-04-01",
    plate: "09-RM-2",
    type: "portacontenedor",
    status: "scheduled",
    trailerBrandAbbr: "DEM",
    trailerYear: "2020",
    fleetMeta: {
      trailerBrandName: "Demo Trailers SA",
      trailerVersion: "portacontenedor",
      equipmentCapacityTons: "32",
      verificationPhysMechDate: "2025-09-18",
      verificationPhysMechCost: 1380,
      lastMaintenanceDate: "2026-03-22",
      lastMaintenanceType: "servicio_completo",
      lastMaintenanceCost: 9800,
      maintenanceEntries: [
        {
          date: "2026-03-22",
          type: "servicio_completo",
          cost: 9800,
          status: "concluido",
          notes: "48 puntos, luces y frenos.",
        },
        {
          date: "2025-10-05",
          type: "medio_servicio",
          cost: 5100,
          status: "concluido",
        },
      ],
      documentVerificationNames: ["verif-fisica-remolque.pdf"],
      insurancePolicyNumber: "EQ-POL-009-2",
      insuranceContractDate: "2025-06-01",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-010-EQ1",
    unitId: "DEMO-TRC-010",
    name: "",
    serialNumber: "EQ-SN-010-1",
    lastServiceDate: "2026-04-01",
    plate: "10-RM-1",
    type: "refrigerado",
    status: "available",
    trailerBrandAbbr: "DEM",
    trailerYear: "2020",
    fleetMeta: {
      trailerBrandName: "Demo Trailers SA",
      trailerVersion: "refrigerado",
      equipmentCapacityTons: "24",
      equipmentOperatedByAgency: true,
      physMechTwoYearExemptStartDate: "2025-02-01",
      lastMaintenanceDate: "2026-03-22",
      lastMaintenanceType: "servicio_completo",
      lastMaintenanceCost: 11200,
      maintenanceEntries: [
        {
          date: "2026-03-22",
          type: "servicio_completo",
          cost: 11200,
          status: "concluido",
          notes: "Equipo de agencia: revisión general.",
        },
      ],
      documentVerificationNames: [],
      insurancePolicyNumber: "EQ-POL-010-1",
      insuranceContractDate: "2025-06-01",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-010-EQ2",
    unitId: "DEMO-TRC-010",
    name: "",
    serialNumber: "EQ-SN-010-2",
    lastServiceDate: "2026-04-01",
    plate: "10-RM-2",
    type: "refrigerado",
    status: "available",
    trailerBrandAbbr: "DEM",
    trailerYear: "2020",
    fleetMeta: {
      trailerBrandName: "Demo Trailers SA",
      trailerVersion: "refrigerado",
      equipmentCapacityTons: "24",
      verificationPhysMechDate: "2025-09-18",
      verificationPhysMechCost: 1380,
      lastMaintenanceDate: "2026-03-22",
      lastMaintenanceType: "servicio_completo",
      lastMaintenanceCost: 9800,
      maintenanceEntries: [
        {
          date: "2026-03-22",
          type: "servicio_completo",
          cost: 9800,
          status: "concluido",
          notes: "48 puntos, luces y frenos.",
        },
        {
          date: "2025-10-05",
          type: "medio_servicio",
          cost: 5100,
          status: "concluido",
        },
      ],
      documentVerificationNames: ["verif-fisica-remolque.pdf"],
      insurancePolicyNumber: "EQ-POL-010-2",
      insuranceContractDate: "2025-06-01",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-011-EQ1",
    unitId: "DEMO-TRC-011",
    name: "",
    serialNumber: "EQ-SN-011-1",
    lastServiceDate: "2026-04-01",
    plate: "11-RM-1",
    type: "plataforma",
    status: "available",
    trailerBrandAbbr: "DEM",
    trailerYear: "2026",
    fleetMeta: {
      trailerBrandName: "Demo Trailers SA",
      trailerVersion: "plataforma",
      equipmentCapacityTons: "24",
      lastMaintenanceDate: "2026-04-10",
      lastMaintenanceType: "medio_servicio",
      lastMaintenanceCost: 6200,
      maintenanceEntries: [
        {
          date: "2026-04-10",
          type: "medio_servicio",
          cost: 6200,
          status: "concluido",
        },
      ],
      documentVerificationNames: [],
      insurancePolicyNumber: "EQ-POL-011-1",
      insuranceContractDate: "2025-06-01",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-011-EQ2",
    unitId: "DEMO-TRC-011",
    name: "",
    serialNumber: "EQ-SN-011-2",
    lastServiceDate: "2026-04-01",
    plate: "11-RM-2",
    type: "plataforma",
    status: "available",
    trailerBrandAbbr: "DEM",
    trailerYear: "2020",
    fleetMeta: {
      trailerBrandName: "Demo Trailers SA",
      trailerVersion: "plataforma",
      equipmentCapacityTons: "24",
      verificationPhysMechDate: "2025-09-18",
      verificationPhysMechCost: 1380,
      lastMaintenanceDate: "2026-03-22",
      lastMaintenanceType: "servicio_completo",
      lastMaintenanceCost: 9800,
      maintenanceEntries: [
        {
          date: "2026-03-22",
          type: "servicio_completo",
          cost: 9800,
          status: "concluido",
          notes: "48 puntos, luces y frenos.",
        },
        {
          date: "2025-10-05",
          type: "medio_servicio",
          cost: 5100,
          status: "concluido",
        },
      ],
      documentVerificationNames: ["verif-fisica-remolque.pdf"],
      insurancePolicyNumber: "EQ-POL-011-2",
      insuranceContractDate: "2025-06-01",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-012-EQ1",
    unitId: "DEMO-TRC-012",
    name: "",
    serialNumber: "EQ-SN-012-1",
    lastServiceDate: "2026-04-01",
    plate: "12-RM-1",
    type: "portacontenedor",
    status: "available",
    trailerBrandAbbr: "DEM",
    trailerYear: "2020",
    fleetMeta: {
      trailerBrandName: "Demo Trailers SA",
      trailerVersion: "portacontenedor",
      equipmentCapacityTons: "32",
      verificationPhysMechDate: "2025-09-18",
      verificationPhysMechCost: 1380,
      lastMaintenanceDate: "2026-03-22",
      lastMaintenanceType: "servicio_completo",
      lastMaintenanceCost: 9800,
      maintenanceEntries: [
        {
          date: "2026-03-22",
          type: "servicio_completo",
          cost: 9800,
          status: "concluido",
          notes: "48 puntos, luces y frenos.",
        },
        {
          date: "2025-10-05",
          type: "medio_servicio",
          cost: 5100,
          status: "concluido",
        },
      ],
      documentVerificationNames: ["verif-fisica-remolque.pdf"],
      insurancePolicyNumber: "EQ-POL-012-1",
      insuranceContractDate: "2025-06-01",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-012-EQ2",
    unitId: "DEMO-TRC-012",
    name: "",
    serialNumber: "EQ-SN-012-2",
    lastServiceDate: "2026-04-01",
    plate: "12-RM-2",
    type: "caja seca",
    status: "available",
    trailerBrandAbbr: "DEM",
    trailerYear: "2020",
    fleetMeta: {
      trailerBrandName: "Demo Trailers SA",
      trailerVersion: "caja seca",
      equipmentCapacityTons: "24",
      verificationPhysMechDate: "2025-09-18",
      verificationPhysMechCost: 1380,
      lastMaintenanceDate: "2026-03-22",
      lastMaintenanceType: "servicio_completo",
      lastMaintenanceCost: 9800,
      maintenanceEntries: [
        {
          date: "2026-03-22",
          type: "servicio_completo",
          cost: 9800,
          status: "concluido",
          notes: "48 puntos, luces y frenos.",
        },
        {
          date: "2025-10-05",
          type: "medio_servicio",
          cost: 5100,
          status: "concluido",
        },
      ],
      documentVerificationNames: ["verif-fisica-remolque.pdf"],
      insurancePolicyNumber: "EQ-POL-012-2",
      insuranceContractDate: "2025-06-01",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-013-EQ1",
    unitId: "DEMO-TRC-013",
    name: "",
    serialNumber: "EQ-SN-013-1",
    lastServiceDate: "2026-04-01",
    plate: "13-RM-1",
    type: "plataforma",
    status: "available",
    trailerBrandAbbr: "DEM",
    trailerYear: "2020",
    fleetMeta: {
      trailerBrandName: "Demo Trailers SA",
      trailerVersion: "plataforma",
      equipmentCapacityTons: "24",
      verificationPhysMechDate: "2025-09-18",
      verificationPhysMechCost: 1380,
      lastMaintenanceDate: "2026-03-22",
      lastMaintenanceType: "servicio_completo",
      lastMaintenanceCost: 9800,
      maintenanceEntries: [
        {
          date: "2026-03-22",
          type: "servicio_completo",
          cost: 9800,
          status: "concluido",
          notes: "48 puntos, luces y frenos.",
        },
        {
          date: "2025-10-05",
          type: "medio_servicio",
          cost: 5100,
          status: "concluido",
        },
      ],
      documentVerificationNames: ["verif-fisica-remolque.pdf"],
      insurancePolicyNumber: "EQ-POL-013-1",
      insuranceContractDate: "2025-06-01",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-013-EQ2",
    unitId: "DEMO-TRC-013",
    name: "",
    serialNumber: "EQ-SN-013-2",
    lastServiceDate: "2026-04-01",
    plate: "13-RM-2",
    type: "plataforma",
    status: "available",
    trailerBrandAbbr: "DEM",
    trailerYear: "2020",
    fleetMeta: {
      trailerBrandName: "Demo Trailers SA",
      trailerVersion: "plataforma",
      equipmentCapacityTons: "24",
      verificationPhysMechDate: "2025-09-18",
      verificationPhysMechCost: 1380,
      lastMaintenanceDate: "2026-03-22",
      lastMaintenanceType: "servicio_completo",
      lastMaintenanceCost: 9800,
      maintenanceEntries: [
        {
          date: "2026-03-22",
          type: "servicio_completo",
          cost: 9800,
          status: "concluido",
          notes: "48 puntos, luces y frenos.",
        },
        {
          date: "2025-10-05",
          type: "medio_servicio",
          cost: 5100,
          status: "concluido",
        },
      ],
      documentVerificationNames: ["verif-fisica-remolque.pdf"],
      insurancePolicyNumber: "EQ-POL-013-2",
      insuranceContractDate: "2025-06-01",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-014-EQ1",
    unitId: "DEMO-TRC-014",
    name: "",
    serialNumber: "EQ-SN-014-1",
    lastServiceDate: "2026-04-01",
    plate: "14-RM-1",
    type: "caja seca",
    status: "available",
    trailerBrandAbbr: "DEM",
    trailerYear: "2020",
    fleetMeta: {
      trailerBrandName: "Demo Trailers SA",
      trailerVersion: "caja seca",
      equipmentCapacityTons: "24",
      verificationPhysMechDate: "2025-09-18",
      verificationPhysMechCost: 1380,
      lastMaintenanceDate: "2026-03-22",
      lastMaintenanceType: "servicio_completo",
      lastMaintenanceCost: 9800,
      maintenanceEntries: [
        {
          date: "2026-03-22",
          type: "servicio_completo",
          cost: 9800,
          status: "concluido",
          notes: "48 puntos, luces y frenos.",
        },
        {
          date: "2025-10-05",
          type: "medio_servicio",
          cost: 5100,
          status: "concluido",
        },
      ],
      documentVerificationNames: ["verif-fisica-remolque.pdf"],
      insurancePolicyNumber: "EQ-POL-014-1",
      insuranceContractDate: "2025-06-01",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-014-EQ2",
    unitId: "DEMO-TRC-014",
    name: "",
    serialNumber: "EQ-SN-014-2",
    lastServiceDate: "2026-04-01",
    plate: "14-RM-2",
    type: "plataforma",
    status: "available",
    trailerBrandAbbr: "DEM",
    trailerYear: "2020",
    fleetMeta: {
      trailerBrandName: "Demo Trailers SA",
      trailerVersion: "plataforma",
      equipmentCapacityTons: "24",
      verificationPhysMechDate: "2025-09-18",
      verificationPhysMechCost: 1380,
      lastMaintenanceDate: "2026-03-22",
      lastMaintenanceType: "servicio_completo",
      lastMaintenanceCost: 9800,
      maintenanceEntries: [
        {
          date: "2026-03-22",
          type: "servicio_completo",
          cost: 9800,
          status: "concluido",
          notes: "48 puntos, luces y frenos.",
        },
        {
          date: "2025-10-05",
          type: "medio_servicio",
          cost: 5100,
          status: "concluido",
        },
      ],
      documentVerificationNames: ["verif-fisica-remolque.pdf"],
      insurancePolicyNumber: "EQ-POL-014-2",
      insuranceContractDate: "2025-06-01",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-015-EQ1",
    unitId: "DEMO-TRC-015",
    name: "",
    serialNumber: "EQ-SN-015-1",
    lastServiceDate: "2026-04-01",
    plate: "15-RM-1",
    type: "plataforma",
    status: "available",
    trailerBrandAbbr: "DEM",
    trailerYear: "2020",
    fleetMeta: {
      trailerBrandName: "Demo Trailers SA",
      trailerVersion: "plataforma",
      equipmentCapacityTons: "24",
      verificationPhysMechDate: "2025-09-18",
      verificationPhysMechCost: 1380,
      lastMaintenanceDate: "2026-03-22",
      lastMaintenanceType: "servicio_completo",
      lastMaintenanceCost: 9800,
      maintenanceEntries: [
        {
          date: "2026-03-22",
          type: "servicio_completo",
          cost: 9800,
          status: "concluido",
          notes: "48 puntos, luces y frenos.",
        },
        {
          date: "2025-10-05",
          type: "medio_servicio",
          cost: 5100,
          status: "concluido",
        },
      ],
      documentVerificationNames: ["verif-fisica-remolque.pdf"],
      insurancePolicyNumber: "EQ-POL-015-1",
      insuranceContractDate: "2025-06-01",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-015-EQ2",
    unitId: "DEMO-TRC-015",
    name: "",
    serialNumber: "EQ-SN-015-2",
    lastServiceDate: "2026-04-01",
    plate: "15-RM-2",
    type: "plataforma",
    status: "available",
    trailerBrandAbbr: "DEM",
    trailerYear: "2020",
    fleetMeta: {
      trailerBrandName: "Demo Trailers SA",
      trailerVersion: "plataforma",
      equipmentCapacityTons: "24",
      verificationPhysMechDate: "2025-09-18",
      verificationPhysMechCost: 1380,
      lastMaintenanceDate: "2026-03-22",
      lastMaintenanceType: "servicio_completo",
      lastMaintenanceCost: 9800,
      maintenanceEntries: [
        {
          date: "2026-03-22",
          type: "servicio_completo",
          cost: 9800,
          status: "concluido",
          notes: "48 puntos, luces y frenos.",
        },
        {
          date: "2025-10-05",
          type: "medio_servicio",
          cost: 5100,
          status: "concluido",
        },
      ],
      documentVerificationNames: ["verif-fisica-remolque.pdf"],
      insurancePolicyNumber: "EQ-POL-015-2",
      insuranceContractDate: "2025-06-01",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-016-EQ1",
    unitId: "DEMO-TRC-016",
    name: "",
    serialNumber: "EQ-SN-016-1",
    lastServiceDate: "2026-04-01",
    plate: "16-RM-1",
    type: "portacontenedor",
    status: "available",
    trailerBrandAbbr: "DEM",
    trailerYear: "2020",
    fleetMeta: {
      trailerBrandName: "Demo Trailers SA",
      trailerVersion: "portacontenedor",
      equipmentCapacityTons: "32",
      verificationPhysMechDate: "2025-09-18",
      verificationPhysMechCost: 1380,
      lastMaintenanceDate: "2026-03-22",
      lastMaintenanceType: "servicio_completo",
      lastMaintenanceCost: 9800,
      maintenanceEntries: [
        {
          date: "2026-03-22",
          type: "servicio_completo",
          cost: 9800,
          status: "concluido",
          notes: "48 puntos, luces y frenos.",
        },
        {
          date: "2025-10-05",
          type: "medio_servicio",
          cost: 5100,
          status: "concluido",
        },
      ],
      documentVerificationNames: ["verif-fisica-remolque.pdf"],
      insurancePolicyNumber: "EQ-POL-016-1",
      insuranceContractDate: "2025-06-01",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-016-EQ2",
    unitId: "DEMO-TRC-016",
    name: "",
    serialNumber: "EQ-SN-016-2",
    lastServiceDate: "2026-04-01",
    plate: "16-RM-2",
    type: "portacontenedor",
    status: "available",
    trailerBrandAbbr: "DEM",
    trailerYear: "2020",
    fleetMeta: {
      trailerBrandName: "Demo Trailers SA",
      trailerVersion: "portacontenedor",
      equipmentCapacityTons: "32",
      verificationPhysMechDate: "2025-09-18",
      verificationPhysMechCost: 1380,
      lastMaintenanceDate: "2026-03-22",
      lastMaintenanceType: "servicio_completo",
      lastMaintenanceCost: 9800,
      maintenanceEntries: [
        {
          date: "2026-03-22",
          type: "servicio_completo",
          cost: 9800,
          status: "concluido",
          notes: "48 puntos, luces y frenos.",
        },
        {
          date: "2025-10-05",
          type: "medio_servicio",
          cost: 5100,
          status: "concluido",
        },
      ],
      documentVerificationNames: ["verif-fisica-remolque.pdf"],
      insurancePolicyNumber: "EQ-POL-016-2",
      insuranceContractDate: "2025-06-01",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-017-EQ1",
    unitId: "DEMO-TRC-017",
    name: "",
    serialNumber: "EQ-SN-017-1",
    lastServiceDate: "2026-04-01",
    plate: "17-RM-1",
    type: "plataforma",
    status: "available",
    trailerBrandAbbr: "DEM",
    trailerYear: "2020",
    fleetMeta: {
      trailerBrandName: "Demo Trailers SA",
      trailerVersion: "plataforma",
      equipmentCapacityTons: "24",
      verificationPhysMechDate: "2025-09-18",
      verificationPhysMechCost: 1380,
      lastMaintenanceDate: "2026-03-22",
      lastMaintenanceType: "servicio_completo",
      lastMaintenanceCost: 9800,
      maintenanceEntries: [
        {
          date: "2026-03-22",
          type: "servicio_completo",
          cost: 9800,
          status: "concluido",
          notes: "48 puntos, luces y frenos.",
        },
        {
          date: "2025-10-05",
          type: "medio_servicio",
          cost: 5100,
          status: "concluido",
        },
      ],
      documentVerificationNames: ["verif-fisica-remolque.pdf"],
      insurancePolicyNumber: "EQ-POL-017-1",
      insuranceContractDate: "2025-06-01",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-017-EQ2",
    unitId: "DEMO-TRC-017",
    name: "",
    serialNumber: "EQ-SN-017-2",
    lastServiceDate: "2026-04-01",
    plate: "17-RM-2",
    type: "caja seca",
    status: "available",
    trailerBrandAbbr: "DEM",
    trailerYear: "2020",
    fleetMeta: {
      trailerBrandName: "Demo Trailers SA",
      trailerVersion: "caja seca",
      equipmentCapacityTons: "24",
      verificationPhysMechDate: "2025-09-18",
      verificationPhysMechCost: 1380,
      lastMaintenanceDate: "2026-03-22",
      lastMaintenanceType: "servicio_completo",
      lastMaintenanceCost: 9800,
      maintenanceEntries: [
        {
          date: "2026-03-22",
          type: "servicio_completo",
          cost: 9800,
          status: "concluido",
          notes: "48 puntos, luces y frenos.",
        },
        {
          date: "2025-10-05",
          type: "medio_servicio",
          cost: 5100,
          status: "concluido",
        },
      ],
      documentVerificationNames: ["verif-fisica-remolque.pdf"],
      insurancePolicyNumber: "EQ-POL-017-2",
      insuranceContractDate: "2025-06-01",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-018-EQ1",
    unitId: "DEMO-TRC-018",
    name: "",
    serialNumber: "EQ-SN-018-1",
    lastServiceDate: "2026-04-01",
    plate: "18-RM-1",
    type: "plataforma",
    status: "available",
    trailerBrandAbbr: "DEM",
    trailerYear: "2020",
    fleetMeta: {
      trailerBrandName: "Demo Trailers SA",
      trailerVersion: "plataforma",
      equipmentCapacityTons: "24",
      verificationPhysMechDate: "2025-09-18",
      verificationPhysMechCost: 1380,
      lastMaintenanceDate: "2026-03-22",
      lastMaintenanceType: "servicio_completo",
      lastMaintenanceCost: 9800,
      maintenanceEntries: [
        {
          date: "2026-03-22",
          type: "servicio_completo",
          cost: 9800,
          status: "concluido",
          notes: "48 puntos, luces y frenos.",
        },
        {
          date: "2025-10-05",
          type: "medio_servicio",
          cost: 5100,
          status: "concluido",
        },
      ],
      documentVerificationNames: ["verif-fisica-remolque.pdf"],
      insurancePolicyNumber: "EQ-POL-018-1",
      insuranceContractDate: "2025-06-01",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-018-EQ2",
    unitId: "DEMO-TRC-018",
    name: "",
    serialNumber: "EQ-SN-018-2",
    lastServiceDate: "2026-04-01",
    plate: "18-RM-2",
    type: "caja seca",
    status: "available",
    trailerBrandAbbr: "DEM",
    trailerYear: "2020",
    fleetMeta: {
      trailerBrandName: "Demo Trailers SA",
      trailerVersion: "caja seca",
      equipmentCapacityTons: "24",
      verificationPhysMechDate: "2025-09-18",
      verificationPhysMechCost: 1380,
      lastMaintenanceDate: "2026-03-22",
      lastMaintenanceType: "servicio_completo",
      lastMaintenanceCost: 9800,
      maintenanceEntries: [
        {
          date: "2026-03-22",
          type: "servicio_completo",
          cost: 9800,
          status: "concluido",
          notes: "48 puntos, luces y frenos.",
        },
        {
          date: "2025-10-05",
          type: "medio_servicio",
          cost: 5100,
          status: "concluido",
        },
      ],
      documentVerificationNames: ["verif-fisica-remolque.pdf"],
      insurancePolicyNumber: "EQ-POL-018-2",
      insuranceContractDate: "2025-06-01",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-019-EQ1",
    unitId: "DEMO-TRC-019",
    name: "",
    serialNumber: "EQ-SN-019-1",
    lastServiceDate: "2026-04-01",
    plate: "19-RM-1",
    type: "caja seca",
    status: "available",
    trailerBrandAbbr: "DEM",
    trailerYear: "2020",
    fleetMeta: {
      trailerBrandName: "Demo Trailers SA",
      trailerVersion: "caja seca",
      equipmentCapacityTons: "24",
      verificationPhysMechDate: "2025-09-18",
      verificationPhysMechCost: 1380,
      lastMaintenanceDate: "2026-03-22",
      lastMaintenanceType: "servicio_completo",
      lastMaintenanceCost: 9800,
      maintenanceEntries: [
        {
          date: "2026-03-22",
          type: "servicio_completo",
          cost: 9800,
          status: "concluido",
          notes: "48 puntos, luces y frenos.",
        },
        {
          date: "2025-10-05",
          type: "medio_servicio",
          cost: 5100,
          status: "concluido",
        },
      ],
      documentVerificationNames: ["verif-fisica-remolque.pdf"],
      insurancePolicyNumber: "EQ-POL-019-1",
      insuranceContractDate: "2025-06-01",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-019-EQ2",
    unitId: "DEMO-TRC-019",
    name: "",
    serialNumber: "EQ-SN-019-2",
    lastServiceDate: "2026-04-01",
    plate: "19-RM-2",
    type: "plataforma",
    status: "available",
    trailerBrandAbbr: "DEM",
    trailerYear: "2020",
    fleetMeta: {
      trailerBrandName: "Demo Trailers SA",
      trailerVersion: "plataforma",
      equipmentCapacityTons: "24",
      verificationPhysMechDate: "2025-09-18",
      verificationPhysMechCost: 1380,
      lastMaintenanceDate: "2026-03-22",
      lastMaintenanceType: "servicio_completo",
      lastMaintenanceCost: 9800,
      maintenanceEntries: [
        {
          date: "2026-03-22",
          type: "servicio_completo",
          cost: 9800,
          status: "concluido",
          notes: "48 puntos, luces y frenos.",
        },
        {
          date: "2025-10-05",
          type: "medio_servicio",
          cost: 5100,
          status: "concluido",
        },
      ],
      documentVerificationNames: ["verif-fisica-remolque.pdf"],
      insurancePolicyNumber: "EQ-POL-019-2",
      insuranceContractDate: "2025-06-01",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-020-EQ1",
    unitId: "DEMO-TRC-020",
    name: "",
    serialNumber: "EQ-SN-020-1",
    lastServiceDate: "2026-04-01",
    plate: "20-RM-1",
    type: "portacontenedor",
    status: "available",
    trailerBrandAbbr: "DEM",
    trailerYear: "2020",
    fleetMeta: {
      trailerBrandName: "Demo Trailers SA",
      trailerVersion: "portacontenedor",
      equipmentCapacityTons: "32",
      verificationPhysMechDate: "2025-09-18",
      verificationPhysMechCost: 1380,
      lastMaintenanceDate: "2026-03-22",
      lastMaintenanceType: "servicio_completo",
      lastMaintenanceCost: 9800,
      maintenanceEntries: [
        {
          date: "2026-03-22",
          type: "servicio_completo",
          cost: 9800,
          status: "concluido",
          notes: "48 puntos, luces y frenos.",
        },
        {
          date: "2025-10-05",
          type: "medio_servicio",
          cost: 5100,
          status: "concluido",
        },
      ],
      documentVerificationNames: ["verif-fisica-remolque.pdf"],
      insurancePolicyNumber: "EQ-POL-020-1",
      insuranceContractDate: "2025-06-01",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-020-EQ2",
    unitId: "DEMO-TRC-020",
    name: "",
    serialNumber: "EQ-SN-020-2",
    lastServiceDate: "2026-04-01",
    plate: "20-RM-2",
    type: "portacontenedor",
    status: "available",
    trailerBrandAbbr: "DEM",
    trailerYear: "2020",
    fleetMeta: {
      trailerBrandName: "Demo Trailers SA",
      trailerVersion: "portacontenedor",
      equipmentCapacityTons: "32",
      verificationPhysMechDate: "2025-09-18",
      verificationPhysMechCost: 1380,
      lastMaintenanceDate: "2026-03-22",
      lastMaintenanceType: "servicio_completo",
      lastMaintenanceCost: 9800,
      maintenanceEntries: [
        {
          date: "2026-03-22",
          type: "servicio_completo",
          cost: 9800,
          status: "concluido",
          notes: "48 puntos, luces y frenos.",
        },
        {
          date: "2025-10-05",
          type: "medio_servicio",
          cost: 5100,
          status: "concluido",
        },
      ],
      documentVerificationNames: ["verif-fisica-remolque.pdf"],
      insurancePolicyNumber: "EQ-POL-020-2",
      insuranceContractDate: "2025-06-01",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-021-EQ1",
    unitId: "DEMO-TRC-021",
    name: "",
    serialNumber: "EQ-SN-021-1",
    lastServiceDate: "2026-04-01",
    plate: "21-RM-1",
    type: "portacontenedor",
    status: "available",
    trailerBrandAbbr: "DEM",
    trailerYear: "2020",
    fleetMeta: {
      trailerBrandName: "Demo Trailers SA",
      trailerVersion: "portacontenedor",
      equipmentCapacityTons: "32",
      verificationPhysMechDate: "2025-09-18",
      verificationPhysMechCost: 1380,
      lastMaintenanceDate: "2026-03-22",
      lastMaintenanceType: "servicio_completo",
      lastMaintenanceCost: 9800,
      maintenanceEntries: [
        {
          date: "2026-03-22",
          type: "servicio_completo",
          cost: 9800,
          status: "concluido",
          notes: "48 puntos, luces y frenos.",
        },
        {
          date: "2025-10-05",
          type: "medio_servicio",
          cost: 5100,
          status: "concluido",
        },
      ],
      documentVerificationNames: ["verif-fisica-remolque.pdf"],
      insurancePolicyNumber: "EQ-POL-021-1",
      insuranceContractDate: "2025-06-01",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-021-EQ2",
    unitId: "DEMO-TRC-021",
    name: "",
    serialNumber: "EQ-SN-021-2",
    lastServiceDate: "2026-04-01",
    plate: "21-RM-2",
    type: "portacontenedor",
    status: "available",
    trailerBrandAbbr: "DEM",
    trailerYear: "2020",
    fleetMeta: {
      trailerBrandName: "Demo Trailers SA",
      trailerVersion: "portacontenedor",
      equipmentCapacityTons: "32",
      verificationPhysMechDate: "2025-09-18",
      verificationPhysMechCost: 1380,
      lastMaintenanceDate: "2026-03-22",
      lastMaintenanceType: "servicio_completo",
      lastMaintenanceCost: 9800,
      maintenanceEntries: [
        {
          date: "2026-03-22",
          type: "servicio_completo",
          cost: 9800,
          status: "concluido",
          notes: "48 puntos, luces y frenos.",
        },
        {
          date: "2025-10-05",
          type: "medio_servicio",
          cost: 5100,
          status: "concluido",
        },
      ],
      documentVerificationNames: ["verif-fisica-remolque.pdf"],
      insurancePolicyNumber: "EQ-POL-021-2",
      insuranceContractDate: "2025-06-01",
      insurancePaymentCadence: "annual"
    }
  },
];
