import { Expense } from '@shared/models/logistics.models';

/**
 * Gastos demo: maniobras en curso e históricas, operaciones de flota y gastos
 * generales (oficina, patio, papelería, servicios).
 */
export const SIM_DB_EXPENSES: Expense[] = [
  // —— Maniobra FL-260510 (en tránsito) ——
  {
    id: 'ex1',
    tripId: 'FL-260510',
    category: 'Combustible',
    amount: 4250.5,
    currency: 'MXN',
    incurredAt: '2026-05-11T12:00:00Z',
    kind: 'fuel',
    description: 'Diésel en ruta Monterrey–Guadalajara',
    vendor: 'PEMEX',
    paymentMethod: 'card',
    invoiceRequired: true,
  },
  {
    id: 'ex2',
    tripId: 'FL-260510',
    category: 'Casetas',
    amount: 890,
    currency: 'MXN',
    incurredAt: '2026-05-11T15:20:00Z',
    kind: 'tolls',
    description: 'Paso por libramiento León',
    paymentMethod: 'card',
    invoiceRequired: false,
  },
  {
    id: 'ex6',
    tripId: 'FL-260510',
    category: 'Viáticos',
    amount: 1850,
    currency: 'MXN',
    incurredAt: '2026-05-11T08:30:00Z',
    kind: 'per_diem',
    description: 'Comida y pernocta operador — tramo MTY–GDL',
    paymentMethod: 'cash',
    invoiceRequired: false,
  },
  {
    id: 'ex16',
    tripId: 'FL-260510',
    category: 'Pago a operador',
    amount: 1200,
    currency: 'MXN',
    incurredAt: '2026-05-10T18:00:00Z',
    kind: 'operator_payment',
    relatedOperatorId: 'op1',
    description: 'Bono de salida maniobra FL-260510',
    paymentMethod: 'transfer',
    invoiceRequired: false,
  },

  // —— Maniobra LV-260512 ——
  {
    id: 'ex7',
    tripId: 'LV-260512',
    category: 'Combustible',
    amount: 3980,
    currency: 'MXN',
    incurredAt: '2026-05-12T11:45:00Z',
    kind: 'fuel',
    description: 'Carga de diésel CDMX–Querétaro',
    vendor: 'BP',
    paymentMethod: 'card',
    invoiceRequired: true,
  },
  {
    id: 'ex8',
    tripId: 'LV-260512',
    category: 'Casetas',
    amount: 1120,
    currency: 'MXN',
    incurredAt: '2026-05-12T14:10:00Z',
    kind: 'tolls',
    description: 'Arco Norte + autopista Qro',
    paymentMethod: 'card',
    invoiceRequired: false,
  },
  {
    id: 'ex17',
    tripId: 'LV-260512',
    category: 'Comisión operador',
    amount: 1350,
    currency: 'MXN',
    incurredAt: '2026-05-12T20:00:00Z',
    kind: 'operator_commission',
    relatedOperatorId: 'op2',
    description: 'Comisión por maniobra sencillo Liverpool',
    paymentMethod: 'transfer',
    invoiceRequired: false,
  },

  // —— Maniobra SR-260514 ——
  {
    id: 'ex9',
    tripId: 'SR-260514',
    category: 'Casetas',
    amount: 640,
    currency: 'MXN',
    incurredAt: '2026-05-13T09:15:00Z',
    kind: 'tolls',
    description: 'Peaje Tijuana–Mexicali',
    paymentMethod: 'card',
    invoiceRequired: false,
  },
  {
    id: 'ex10',
    tripId: 'SR-260514',
    category: 'Combustible',
    amount: 2890,
    currency: 'MXN',
    incurredAt: '2026-05-13T10:30:00Z',
    kind: 'fuel',
    description: 'Recarga diésel frontera',
    vendor: 'G500',
    paymentMethod: 'card',
    invoiceRequired: true,
  },

  // —— Otras maniobras en curso ——
  {
    id: 'ex11',
    tripId: 'KC-260516',
    category: 'Hospedaje',
    amount: 980,
    currency: 'MXN',
    incurredAt: '2026-05-14T22:00:00Z',
    kind: 'lodging',
    description: 'Hotel operador en ruta foránea',
    vendor: 'City Express',
    paymentMethod: 'card',
    invoiceRequired: true,
  },
  {
    id: 'ex12',
    tripId: 'GM-260518',
    category: 'Combustible',
    amount: 5120,
    currency: 'MXN',
    incurredAt: '2026-05-15T07:20:00Z',
    kind: 'fuel',
    description: 'Tanque lleno salida patio Guadalajara',
    vendor: 'PEMEX',
    paymentMethod: 'card',
    invoiceRequired: true,
  },
  {
    id: 'ex13',
    tripId: 'GM-260518',
    category: 'Maniobras en patio',
    amount: 450,
    currency: 'MXN',
    incurredAt: '2026-05-15T06:45:00Z',
    kind: 'other',
    description: 'Movimiento interno y enganche en terminal',
    vendor: 'Patio TerminalOps GDL',
    paymentMethod: 'cash',
    invoiceRequired: false,
  },

  // —— Maniobras completadas ——
  {
    id: 'ex14',
    tripId: 'CC-260505',
    category: 'Casetas',
    amount: 1560,
    currency: 'MXN',
    incurredAt: '2026-05-06T16:40:00Z',
    kind: 'tolls',
    description: 'Casetas ida y vuelta circuito cerrado',
    paymentMethod: 'card',
    invoiceRequired: false,
  },
  {
    id: 'ex15',
    tripId: 'PF-260507',
    category: 'Combustible',
    amount: 3675,
    currency: 'MXN',
    incurredAt: '2026-05-08T13:00:00Z',
    kind: 'fuel',
    description: 'Diésel maniobra Procter PF-260507',
    vendor: 'Mobil',
    paymentMethod: 'card',
    invoiceRequired: true,
  },
  {
    id: 'ex18',
    tripId: 'FL-260513',
    category: 'Viáticos',
    amount: 1420,
    currency: 'MXN',
    incurredAt: '2026-05-09T19:30:00Z',
    kind: 'per_diem',
    description: 'Alimentos operador en tránsito',
    paymentMethod: 'cash',
    invoiceRequired: false,
  },
  {
    id: 'ex19',
    tripId: 'SR-260515',
    category: 'Retención / revisión',
    amount: 800,
    currency: 'MXN',
    incurredAt: '2026-05-10T11:00:00Z',
    kind: 'other',
    description: 'Tiempo extra por revisión SCT en carretera',
    paymentMethod: 'cash',
    invoiceRequired: false,
  },
  {
    id: 'ex20',
    tripId: 'WM-260517',
    category: 'Grúa',
    amount: 4500,
    currency: 'MXN',
    incurredAt: '2026-05-12T03:15:00Z',
    kind: 'other',
    description: 'Asistencia en ruta — pinchazo en eje',
    vendor: 'Grúas del Bajío',
    paymentMethod: 'transfer',
    invoiceRequired: true,
  },
  {
    id: 'ex21',
    tripId: 'BC-260519',
    category: 'Casetas',
    amount: 720,
    currency: 'MXN',
    incurredAt: '2026-05-11T17:55:00Z',
    kind: 'tolls',
    description: 'Peajes autopista costera',
    paymentMethod: 'card',
    invoiceRequired: false,
  },

  // —— Flota (sin maniobra) ——
  {
    id: 'ex3',
    tripId: '',
    category: 'Servicio de frenos',
    amount: 12800,
    currency: 'MXN',
    incurredAt: '2026-05-18',
    kind: 'maintenance',
    maintenanceTarget: 'unit',
    relatedUnitId: 'DEMO-TRC-001',
    description: 'Rectificación de discos y pastillas',
    vendor: 'Taller Ruta Norte',
    paymentMethod: 'transfer',
    invoiceRequired: true,
  },
  {
    id: 'ex4',
    tripId: '',
    category: 'Renovación póliza equipo',
    amount: 18500,
    currency: 'MXN',
    incurredAt: '2026-03-01',
    kind: 'insurance',
    insuranceTarget: 'equipment',
    relatedEquipmentId: 'DEMO-TRC-001-EQ1',
    vendor: 'GNP Seguros',
    paymentMethod: 'transfer',
    invoiceRequired: true,
  },
  {
    id: 'ex5',
    tripId: '',
    category: 'Verificación físico-mecánica',
    amount: 650,
    currency: 'MXN',
    incurredAt: '2026-02-10',
    kind: 'verification',
    relatedUnitId: 'DEMO-TRC-001',
    verificationScope: 'phys_mech',
    vendor: 'Verificentro Regulado',
    paymentMethod: 'cash',
    invoiceRequired: false,
  },
  {
    id: 'ex22',
    tripId: '',
    category: 'GPS / telemetría',
    amount: 3200,
    currency: 'MXN',
    incurredAt: '2026-05-01',
    kind: 'gps',
    relatedUnitId: 'DEMO-TRC-002',
    description: 'Suscripción mensual plataforma rastreo',
    vendor: 'Samsara MX',
    paymentMethod: 'card',
    invoiceRequired: true,
  },

  // —— Gastos generales (oficina, patio, administración) ——
  {
    id: 'ex23',
    tripId: '',
    category: 'Renta de oficina',
    amount: 28500,
    currency: 'MXN',
    incurredAt: '2026-05-01',
    kind: 'other',
    description: 'Renta mayo — oficinas corporativas Monterrey',
    vendor: 'Inmobiliaria Valle Oriente',
    paymentMethod: 'transfer',
    invoiceRequired: true,
  },
  {
    id: 'ex24',
    tripId: '',
    category: 'Renta de patio',
    amount: 42000,
    currency: 'MXN',
    incurredAt: '2026-05-01',
    kind: 'other',
    description: 'Arrendamiento patio operativo Guadalajara (40 cajones)',
    vendor: 'Parque Industrial El Águila',
    paymentMethod: 'transfer',
    invoiceRequired: true,
  },
  {
    id: 'ex25',
    tripId: '',
    category: 'Papelería',
    amount: 1840,
    currency: 'MXN',
    incurredAt: '2026-05-08',
    kind: 'other',
    description: 'Formatos, toner y material de oficina',
    vendor: 'Office Depot',
    paymentMethod: 'card',
    invoiceRequired: true,
  },
  {
    id: 'ex26',
    tripId: '',
    category: 'Servicios públicos',
    amount: 5620,
    currency: 'MXN',
    incurredAt: '2026-05-12',
    kind: 'other',
    description: 'Luz y agua — oficina y módulo de patio MTY',
    vendor: 'CFE / SIAPA',
    paymentMethod: 'transfer',
    invoiceRequired: true,
  },
  {
    id: 'ex27',
    tripId: '',
    category: 'Internet y telefonía',
    amount: 2890,
    currency: 'MXN',
    incurredAt: '2026-05-05',
    kind: 'other',
    description: 'Enlaces dedicados y líneas móviles operaciones',
    vendor: 'Telmex Empresarial',
    paymentMethod: 'card',
    invoiceRequired: true,
  },
  {
    id: 'ex28',
    tripId: '',
    category: 'Limpieza',
    amount: 3200,
    currency: 'MXN',
    incurredAt: '2026-05-15',
    kind: 'other',
    description: 'Limpieza quincenal oficinas y sanitarios de patio',
    vendor: 'Servicios Integrales del Norte',
    paymentMethod: 'transfer',
    invoiceRequired: true,
  },
  {
    id: 'ex29',
    tripId: '',
    category: 'Seguridad',
    amount: 9800,
    currency: 'MXN',
    incurredAt: '2026-05-01',
    kind: 'other',
    description: 'Vigilancia nocturna patio GDL',
    vendor: 'Seguridad Patrimonial MX',
    paymentMethod: 'transfer',
    invoiceRequired: true,
  },
  {
    id: 'ex30',
    tripId: '',
    category: 'TAG / peajes',
    amount: 15000,
    currency: 'MXN',
    incurredAt: '2026-05-03',
    kind: 'other',
    description: 'Recarga saldo TAG flota (cuenta corporativa)',
    vendor: 'PASE',
    paymentMethod: 'transfer',
    invoiceRequired: false,
  },
  {
    id: 'ex31',
    tripId: '',
    category: 'Agua potable patio',
    amount: 890,
    currency: 'MXN',
    incurredAt: '2026-05-14',
    kind: 'other',
    description: 'Pipa y garrafones para área de operadores',
    vendor: 'Agua Purificada del Centro',
    paymentMethod: 'cash',
    invoiceRequired: false,
  },
  {
    id: 'ex32',
    tripId: '',
    category: 'Contabilidad',
    amount: 7500,
    currency: 'MXN',
    incurredAt: '2026-05-10',
    kind: 'other',
    description: 'Honorarios despacho contable — mayo',
    vendor: 'Despacho López & Asociados',
    paymentMethod: 'transfer',
    invoiceRequired: true,
  },
];
