import { defaultOperatorShell } from '@features/operators/utils/operator-payload-defaults';
import { Operator } from '@shared/models/logistics.models';

export const SIM_DB_OPERATORS: Operator[] = [
  defaultOperatorShell({
    id: 'op1',
    portalUsername: 'mlopez',
    name: 'María López',
    birthDate: '1988-03-22',
    curp: 'LOME880322MDFRRR09',
    rfc: 'LOME880322U76',
    licenseNumber: 'CMX-778899',
    licenseExpiresOn: '2027-06-18',
    licenseType: 'state',
    licenseEndorsements: '',
    phone: '+52 55 1234 5678',
    phoneSecondary: '+52 55 9000 1111',
    address: 'Col. Del Valle, CDMX',
    companyHireDate: '2018-06-01',
    employmentContractType: 'indefinite',
    status: 'in_use',
    insuranceKind: 'public',
    emergencyContact: {
      name: 'Jorge López',
      relationship: 'spouse',
      phone: '+52 55 2222 3333',
      email: 'jorge.lopez@example.com',
      authorizedMedicalInfo: true,
    },
    publicInsurance: {
      nss: '45987654321',
      imssAltaDate: '2018-05-01',
      infonavit: true,
      infonavitCreditNumber: '1298765432109',
      fonacot: false,
      fonacotCreditNumber: '',
      notes: '',
    },
    privateInsurance: {
      carrier: '',
      policyNumber: '',
      validFrom: '',
      validTo: '',
      premiumAmount: '',
      premiumPeriod: '',
      deductibleNotes: '',
      planSummary: '',
    },
    documents: [
      {
        id: 'op1-doc-op',
        fileName: 'contrato_indeterminado.pdf',
        slot: 'operation',
        addedAt: '2018-06-01',
      },
      {
        id: 'op1-doc-ins',
        fileName: 'constancia_movimientos_afiliatorios.pdf',
        slot: 'insurance',
        addedAt: '2018-05-01',
      },
    ],
  }),
  defaultOperatorShell({
    id: 'op2',
    portalUsername: 'cruiz',
    name: 'Carlos Ruiz',
    birthDate: '1992-11-08',
    curp: 'RUCN921108HDFZRR03',
    rfc: 'RUCN921108',
    licenseNumber: 'CMX-445566',
    licenseExpiresOn: '2026-11-02',
    licenseType: 'federal',
    licenseEndorsements: 'Autotransporte federal',
    phone: '+52 81 9876 5432',
    phoneSecondary: '',
    address: 'San Pedro Garza García, NL',
    companyHireDate: '2021-03-15',
    employmentContractType: 'indefinite',
    status: 'in_use',
    insuranceKind: 'private',
    emergencyContact: {
      name: 'Laura Ruiz',
      relationship: 'parent',
      phone: '+52 81 4444 5555',
      email: '',
      authorizedMedicalInfo: false,
    },
    publicInsurance: {
      nss: '',
      imssAltaDate: '',
      infonavit: false,
      infonavitCreditNumber: '',
      fonacot: false,
      fonacotCreditNumber: '',
      notes: '',
    },
    privateInsurance: {
      carrier: 'GNP Seguros',
      policyNumber: 'GNP-MED-998877',
      validFrom: '2025-01-01',
      validTo: '2025-12-31',
      premiumAmount: '12400',
      premiumPeriod: 'annual',
      deductibleNotes: 'Deducible 5% UMA',
      planSummary: 'Plan médico mayor + accidentes',
    },
    documents: [],
  }),
  defaultOperatorShell({
    id: 'op3',
    portalUsername: 'amartinez',
    name: 'Ana Martínez',
    birthDate: '1995-07-14',
    curp: 'MAAN950714MDFRRN02',
    rfc: '',
    licenseNumber: 'TIJ-990011',
    licenseExpiresOn: '2028-01-14',
    licenseType: 'both',
    licenseEndorsements: '',
    phone: '+52 664 555 1212',
    phoneSecondary: '',
    address: 'Tijuana, BC',
    companyHireDate: '2025-11-01',
    employmentContractType: 'temporary',
    status: 'in_use',
    insuranceKind: 'none',
    emergencyContact: {
      name: 'Rosa Martínez',
      relationship: 'parent',
      phone: '+52 664 7777 8888',
      email: 'rosa.m@example.com',
      authorizedMedicalInfo: false,
    },
  }),
  defaultOperatorShell({
    id: 'op4',
    name: 'Luis Hernández',
    birthDate: '1985-01-30',
    curp: 'HEHL850130HDFRRS08',
    rfc: 'HEHL850130',
    licenseNumber: 'PUE-332211',
    licenseExpiresOn: '2026-04-22',
    licenseType: 'unspecified',
    licenseEndorsements: '',
    phone: '+52 222 444 8899',
    phoneSecondary: '',
    address: 'Puebla, Pue.',
    companyHireDate: '2020-02-15',
    employmentContractType: 'indefinite',
    status: 'available',
    insuranceKind: 'public',
    emergencyContact: {
      name: 'Miguel Hernández',
      relationship: 'sibling',
      phone: '+52 222 333 2211',
      email: '',
      authorizedMedicalInfo: false,
    },
    publicInsurance: {
      nss: '12098765432',
      imssAltaDate: '2020-02-15',
      infonavit: false,
      infonavitCreditNumber: '',
      fonacot: true,
      fonacotCreditNumber: 'FCOT-2020-884422',
      notes: 'Descuento FONACOT activo',
    },
  }),
  defaultOperatorShell({
    id: 'op5',
    name: 'Patricia Gómez',
    birthDate: '1990-12-05',
    curp: 'GOMP901205MDFRTC01',
    rfc: 'GOMP901205',
    licenseNumber: 'SLW-556677',
    licenseExpiresOn: '2027-09-30',
    licenseType: 'state',
    licenseEndorsements: '',
    phone: '+52 844 333 4455',
    phoneSecondary: '+52 844 1111 2222',
    address: 'Saltillo, Coah.',
    companyHireDate: '2019-01-10',
    employmentContractType: 'indefinite',
    status: 'available',
    insuranceKind: 'private',
    emergencyContact: {
      name: 'Andrea Gómez',
      relationship: 'child',
      phone: '+52 844 6666 7777',
      email: 'andrea.gomez@example.com',
      authorizedMedicalInfo: true,
    },
    publicInsurance: {
      nss: '',
      imssAltaDate: '',
      infonavit: false,
      infonavitCreditNumber: '',
      fonacot: false,
      fonacotCreditNumber: '',
      notes: '',
    },
    privateInsurance: {
      carrier: 'AXA Seguros',
      policyNumber: 'AXA-552211',
      validFrom: '2024-06-01',
      validTo: '2026-05-31',
      premiumAmount: '980',
      premiumPeriod: 'monthly',
      deductibleNotes: '',
      planSummary: 'Colectivo familiar',
    },
  }),
  defaultOperatorShell({
    id: 'op6',
    portalUsername: 'rvega',
    name: 'Ricardo Vega',
    birthDate: '1987-09-18',
    curp: 'VEHR870918HDFGRC04',
    rfc: 'VEHR870918',
    licenseNumber: 'GDL-112233',
    licenseExpiresOn: '2027-03-10',
    licenseType: 'federal',
    licenseEndorsements: 'Autotransporte federal',
    phone: '+52 33 2100 8899',
    phoneSecondary: '',
    address: 'Zapopan, Jal.',
    companyHireDate: '2017-04-01',
    employmentContractType: 'indefinite',
    status: 'in_use',
    insuranceKind: 'public',
    emergencyContact: {
      name: 'Mariana Vega',
      relationship: 'spouse',
      phone: '+52 33 2100 9900',
      email: 'mariana.vega@example.com',
      authorizedMedicalInfo: true,
    },
    publicInsurance: {
      nss: '55112233445',
      imssAltaDate: '2017-03-15',
      infonavit: false,
      infonavitCreditNumber: '',
      fonacot: false,
      fonacotCreditNumber: '',
      notes: '',
    },
  }),
  defaultOperatorShell({
    id: 'op7',
    portalUsername: 'snunez',
    name: 'Sofía Núñez',
    birthDate: '1993-04-25',
    curp: 'NUSF930425MDFXRF07',
    rfc: 'NUSF930425',
    licenseNumber: 'MTY-998877',
    licenseExpiresOn: '2026-12-01',
    licenseType: 'state',
    licenseEndorsements: '',
    phone: '+52 81 7700 4455',
    phoneSecondary: '',
    address: 'San Nicolás de los Garza, NL',
    companyHireDate: '2022-08-01',
    employmentContractType: 'indefinite',
    status: 'in_use',
    insuranceKind: 'private',
    emergencyContact: {
      name: 'Roberto Núñez',
      relationship: 'parent',
      phone: '+52 81 7700 3322',
      email: '',
      authorizedMedicalInfo: false,
    },
    publicInsurance: {
      nss: '',
      imssAltaDate: '',
      infonavit: false,
      infonavitCreditNumber: '',
      fonacot: false,
      fonacotCreditNumber: '',
      notes: '',
    },
    privateInsurance: {
      carrier: 'MetLife México',
      policyNumber: 'ML-778899',
      validFrom: '2025-01-01',
      validTo: '2025-12-31',
      premiumAmount: '850',
      premiumPeriod: 'monthly',
      deductibleNotes: '',
      planSummary: 'Gastos médicos mayores',
    },
  }),
  defaultOperatorShell({
    id: 'op8',
    portalUsername: 'dcampos',
    name: 'Diego Campos',
    birthDate: '1991-02-11',
    curp: 'CADG910211HDFRMD09',
    rfc: 'CADG910211',
    licenseNumber: 'QRO-654321',
    licenseExpiresOn: '2028-05-20',
    licenseType: 'both',
    licenseEndorsements: '',
    phone: '+52 442 3300 1122',
    phoneSecondary: '+52 442 3300 3344',
    address: 'Santiago de Querétaro, Qro.',
    companyHireDate: '2019-11-20',
    employmentContractType: 'indefinite',
    status: 'scheduled',
    insuranceKind: 'public',
    emergencyContact: {
      name: 'Lucía Campos',
      relationship: 'sibling',
      phone: '+52 442 3300 5566',
      email: 'lucia.campos@example.com',
      authorizedMedicalInfo: true,
    },
    publicInsurance: {
      nss: '77889900112',
      imssAltaDate: '2019-11-01',
      infonavit: true,
      infonavitCreditNumber: '9988776655443',
      fonacot: false,
      fonacotCreditNumber: '',
      notes: '',
    },
  }),
  defaultOperatorShell({
    id: 'op9',
    portalUsername: 'erios',
    name: 'Elena Ríos',
    birthDate: '1989-06-30',
    curp: 'RIEL890630MDFXLN08',
    rfc: 'RIEL890630',
    licenseNumber: 'VER-887766',
    licenseExpiresOn: '2027-01-15',
    licenseType: 'state',
    licenseEndorsements: '',
    phone: '+52 229 4400 7788',
    phoneSecondary: '',
    address: 'Veracruz, Ver.',
    companyHireDate: '2021-01-05',
    employmentContractType: 'indefinite',
    status: 'scheduled',
    insuranceKind: 'public',
    emergencyContact: {
      name: 'Héctor Ríos',
      relationship: 'spouse',
      phone: '+52 229 4400 9900',
      email: 'hector.rios@example.com',
      authorizedMedicalInfo: false,
    },
    publicInsurance: {
      nss: '66778899001',
      imssAltaDate: '2021-01-05',
      infonavit: false,
      infonavitCreditNumber: '',
      fonacot: true,
      fonacotCreditNumber: 'FCOT-2021-112233',
      notes: '',
    },
  }),
];
