import { Trip } from '@shared/models/logistics.models';

/**
 * Maniobras demo (4–30 may 2026): 21 registros, estatus mezclados.
 * Operadores op1–op3 (en curso), op6–op7 (en curso / programadas), op8–op9 (programadas + historial);
 * op4–op5 disponibles en bolsa. Cada viaje usa unitId y equipment[] existentes en units / equipment.
 * Full = 2 remolques del mismo tractor; sencillo o plana = 1.
 */
export const SIM_DB_TRIPS: Trip[] = [
  {
    id: "FL-260510",
    maneuverCode: "FL-260510",
    origin: "Monterrey",
    destination: "Guadalajara",
    clientName: "FEMSA Logística",
    clientId: "cli-femsa",
    unitId: "DEMO-TRC-001",
    operatorId: "op1",
    status: "in_transit",
    programmedAt: "2026-05-10T14:00:00Z",
    scheduledAt: "2026-05-11T08:00:00Z",
    operationType: "full",
    loadType: "lleno",
    containerType: "40ft",
    approximateWeightTons: "22",
    equipment: ["DEMO-TRC-001-EQ1","DEMO-TRC-001-EQ2"],
    departureAt: "2026-05-11T07:45:00Z",
    arrivedAt: null,
    returnAt: null,
    creditDays: 30,
    hasIncident: true,
    incidents: [
      {
        id: "inc-fl-cold",
        description:
          "Temperatura de remolque refrigerado fuera de rango (−2 °C reportados, meta 0–4 °C).",
        occurredAt: "2026-05-11T18:20:00Z",
        postedBy: "mlopez",
              severity: "critical",
      },
      {
        id: "inc-fl-gps",
        description:
          "Pérdida de señal GPS mayor a 20 minutos en tramo León–Aguascalientes.",
        occurredAt: "2026-05-11T14:05:00Z",
        postedBy: "jlopez",
              severity: "critical",
      },
    ],
    routeDistanceKm: 200,
    maneuverKind: "Foránea",
    originPostalCode: "64000",
    originCityMunicipality: "Monterrey, MX",
    destinationPostalCode: "44100",
    destinationCityMunicipality: "Guadalajara, MX",
    operatorLicenseNumber: "CMX-778899",
    operatorLicenseExpiresLabel: "18 de junio de 2027",
    dieselLiters: "400",
    dieselAmount: "9000",
    casetasAmount: "800",
    operatorQuota: "1200",
    clientCharge: "35000",
    paymentMethod: "transfer",
    requiresInvoice: true,
    hasClientBilling: true,
    attachedDocumentFileNames: ["CP-FL-260510.pdf"],
  },
  {
    id: "LV-260512",
    maneuverCode: "LV-260512",
    origin: "Ciudad de México",
    destination: "Querétaro",
    clientName: "Liverpool",
    clientId: "cli-liverpool",
    unitId: "DEMO-TRC-002",
    operatorId: "op2",
    status: "in_transit",
    programmedAt: "2026-05-11T14:00:00Z",
    scheduledAt: "2026-05-12T08:00:00Z",
    operationType: "sencillo",
    loadType: "vacio",
    containerType: "na",
    approximateWeightTons: "",
    equipment: ["DEMO-TRC-002-EQ1"],
    departureAt: "2026-05-12T07:45:00Z",
    arrivedAt: null,
    returnAt: null,
    creditDays: 30,
    hasIncident: true,
    incidents: [
      {
        id: "inc-lv-driver",
        description:
          "Operador cercano al límite de tiempo de conducción; se solicitó parada de descanso.",
        occurredAt: "2026-05-12T16:30:00Z",
        postedBy: "cruiz",
              severity: "high",
      },
    ],
    routeDistanceKm: 240,
    maneuverKind: "Foránea",
    originPostalCode: "64000",
    originCityMunicipality: "Ciudad de México, MX",
    destinationPostalCode: "44100",
    destinationCityMunicipality: "Querétaro, MX",
    operatorLicenseNumber: "CMX-445566",
    operatorLicenseExpiresLabel: "2 de noviembre de 2026",
    dieselLiters: "480",
    dieselAmount: "10200",
    casetasAmount: "1000",
    operatorQuota: "1350",
    clientCharge: "39000",
    paymentMethod: "transfer",
    requiresInvoice: true,
    hasClientBilling: true,
    attachedDocumentFileNames: ["CP-LV-260512.pdf"],
  },
  {
    id: "SR-260514",
    maneuverCode: "SR-260514",
    origin: "Tijuana",
    destination: "Mexicali",
    clientName: "Organización Soriana",
    clientId: "cli-soriana",
    unitId: "DEMO-TRC-003",
    operatorId: "op3",
    status: "in_transit",
    programmedAt: "2026-05-12T14:00:00Z",
    scheduledAt: "2026-05-13T08:00:00Z",
    operationType: "plana",
    loadType: "lleno",
    containerType: "20ft",
    approximateWeightTons: "12",
    equipment: ["DEMO-TRC-003-EQ1"],
    departureAt: "2026-05-13T07:45:00Z",
    arrivedAt: null,
    returnAt: null,
    creditDays: 30,
    hasIncident: true,
    incidents: [
      {
        id: "inc-sr-sct",
        description:
          "Revisión SCT en carretera: manifiesto y permisos incompletos en punto de control.",
        occurredAt: "2026-05-13T09:20:00Z",
        postedBy: "gvelasco",
              severity: "high",
      },
      {
        id: "inc-demo-caseta",
        description: "Retraso en caseta por revisión aleatoria de la Guardia Nacional.",
        occurredAt: "2026-05-13T07:45:00Z",
        postedBy: "amartinez",
              severity: "high",
      },
    ],
    routeDistanceKm: 280,
    maneuverKind: "Foránea",
    originPostalCode: "64000",
    originCityMunicipality: "Tijuana, MX",
    destinationPostalCode: "44100",
    destinationCityMunicipality: "Mexicali, MX",
    operatorLicenseNumber: "TIJ-990011",
    operatorLicenseExpiresLabel: "14 de enero de 2028",
    dieselLiters: "560",
    dieselAmount: "11400",
    casetasAmount: "1200",
    operatorQuota: "1500",
    clientCharge: "43000",
    paymentMethod: "transfer",
    requiresInvoice: true,
    hasClientBilling: true,
    attachedDocumentFileNames: ["CP-SR-260514.pdf"],
  },
  {
    id: "KC-260516",
    maneuverCode: "KC-260516",
    origin: "Puebla",
    destination: "Veracruz",
    clientName: "Kimberly-Clark",
    clientId: "cli-kc",
    unitId: "DEMO-TRC-004",
    operatorId: "op6",
    status: "in_transit",
    programmedAt: "2026-05-13T14:00:00Z",
    scheduledAt: "2026-05-14T08:00:00Z",
    operationType: "full",
    loadType: "lleno",
    containerType: "40hc",
    approximateWeightTons: "19",
    equipment: ["DEMO-TRC-004-EQ1","DEMO-TRC-004-EQ2"],
    departureAt: "2026-05-14T07:45:00Z",
    arrivedAt: null,
    returnAt: null,
    creditDays: 30,
    hasIncident: true,
    incidents: [
      {
        id: "inc-kc-route",
        description:
          "Desviación de ruta no autorizada detectada por telemetría en corredor Puebla–Veracruz.",
        occurredAt: "2026-05-14T20:10:00Z",
        postedBy: "rvega",
              severity: "critical",
      },
    ],
    routeDistanceKm: 320,
    maneuverKind: "Foránea",
    originPostalCode: "64000",
    originCityMunicipality: "Puebla, MX",
    destinationPostalCode: "44100",
    destinationCityMunicipality: "Veracruz, MX",
    operatorLicenseNumber: "GDL-112233",
    operatorLicenseExpiresLabel: "10 de marzo de 2027",
    dieselLiters: "640",
    dieselAmount: "12600",
    casetasAmount: "1400",
    operatorQuota: "1650",
    clientCharge: "47000",
    paymentMethod: "transfer",
    requiresInvoice: true,
    hasClientBilling: true,
    attachedDocumentFileNames: ["CP-KC-260516.pdf"],
  },
  {
    id: "GM-260518",
    maneuverCode: "GM-260518",
    origin: "Mérida",
    destination: "Cancún",
    clientName: "Grupo Modelo",
    clientId: "cli-modelo",
    unitId: "DEMO-TRC-005",
    operatorId: "op7",
    status: "in_transit",
    programmedAt: "2026-05-14T14:00:00Z",
    scheduledAt: "2026-05-15T08:00:00Z",
    operationType: "sencillo",
    loadType: "lleno",
    containerType: "40ft",
    approximateWeightTons: "15",
    equipment: ["DEMO-TRC-005-EQ1"],
    departureAt: "2026-05-15T07:45:00Z",
    arrivedAt: null,
    returnAt: null,
    creditDays: 30,
    hasIncident: true,
    incidents: [
      {
        id: "inc-gm-brakes",
        description:
          "Falla en sistema de frenos reportada en parada de seguridad; taller en ruta en curso.",
        occurredAt: "2026-05-15T11:00:00Z",
        postedBy: "snunez",
              severity: "critical",
      },
    ],
    routeDistanceKm: 360,
    maneuverKind: "Foránea",
    originPostalCode: "64000",
    originCityMunicipality: "Mérida, MX",
    destinationPostalCode: "44100",
    destinationCityMunicipality: "Cancún, MX",
    operatorLicenseNumber: "MTY-998877",
    operatorLicenseExpiresLabel: "1 de diciembre de 2026",
    dieselLiters: "720",
    dieselAmount: "13800",
    casetasAmount: "1600",
    operatorQuota: "1800",
    clientCharge: "51000",
    paymentMethod: "transfer",
    requiresInvoice: true,
    hasClientBilling: true,
    attachedDocumentFileNames: ["CP-GM-260518.pdf"],
  },
  {
    id: "BC-260520",
    maneuverCode: "BC-260520",
    origin: "León",
    destination: "Aguascalientes",
    clientName: "Industrias Bachoco",
    clientId: "cli-bachoco",
    unitId: "DEMO-TRC-006",
    operatorId: "op8",
    status: "scheduled",
    programmedAt: "2026-05-20T16:00:00Z",
    scheduledAt: "2026-05-22T10:00:00Z",
    operationType: "full",
    loadType: "vacio",
    containerType: "40ft",
    approximateWeightTons: "",
    equipment: ["DEMO-TRC-006-EQ1","DEMO-TRC-006-EQ2"],
    departureAt: null,
    arrivedAt: null,
    returnAt: null,
    creditDays: 45,
    hasIncident: false,
    routeDistanceKm: 150,
    maneuverKind: "Foránea",
    originPostalCode: "37000",
    originCityMunicipality: "León, MX",
    destinationPostalCode: "20000",
    destinationCityMunicipality: "Aguascalientes, MX",
    operatorLicenseNumber: "QRO-654321",
    operatorLicenseExpiresLabel: "20 de mayo de 2028",
    dieselLiters: "300",
    dieselAmount: "7000",
    casetasAmount: "600",
    operatorQuota: "1000",
    clientCharge: "28000",
    paymentMethod: "transfer",
    requiresInvoice: true,
    hasClientBilling: true,
    attachedDocumentFileNames: ["Prog-BC-260520.pdf"],
  },
  {
    id: "PE-260522",
    maneuverCode: "PE-260522",
    origin: "Saltillo",
    destination: "Torreón",
    clientName: "Peñoles",
    clientId: "cli-penoles",
    unitId: "DEMO-TRC-007",
    operatorId: "op9",
    status: "scheduled",
    programmedAt: "2026-05-22T16:00:00Z",
    scheduledAt: "2026-05-24T10:00:00Z",
    operationType: "sencillo",
    loadType: "lleno",
    containerType: "na",
    approximateWeightTons: "9",
    equipment: ["DEMO-TRC-007-EQ1"],
    departureAt: null,
    arrivedAt: null,
    returnAt: null,
    creditDays: 45,
    hasIncident: false,
    routeDistanceKm: 205,
    maneuverKind: "Foránea",
    originPostalCode: "37000",
    originCityMunicipality: "Saltillo, MX",
    destinationPostalCode: "20000",
    destinationCityMunicipality: "Torreón, MX",
    operatorLicenseNumber: "VER-887766",
    operatorLicenseExpiresLabel: "15 de enero de 2027",
    dieselLiters: "350",
    dieselAmount: "7900",
    casetasAmount: "700",
    operatorQuota: "1100",
    clientCharge: "31500",
    paymentMethod: "transfer",
    requiresInvoice: true,
    hasClientBilling: true,
    attachedDocumentFileNames: ["Prog-PE-260522.pdf"],
  },
  {
    id: "SG-260524",
    maneuverCode: "SG-260524",
    origin: "Morelia",
    destination: "Colima",
    clientName: "Sigma Alimentos",
    clientId: "cli-sigma",
    unitId: "DEMO-TRC-008",
    operatorId: "op6",
    status: "scheduled",
    programmedAt: "2026-05-24T16:00:00Z",
    scheduledAt: "2026-05-26T10:00:00Z",
    operationType: "plana",
    loadType: "lleno",
    containerType: "20ft",
    approximateWeightTons: "11",
    equipment: ["DEMO-TRC-008-EQ1"],
    departureAt: null,
    arrivedAt: null,
    returnAt: null,
    creditDays: 45,
    hasIncident: false,
    routeDistanceKm: 260,
    maneuverKind: "Foránea",
    originPostalCode: "37000",
    originCityMunicipality: "Morelia, MX",
    destinationPostalCode: "20000",
    destinationCityMunicipality: "Colima, MX",
    operatorLicenseNumber: "CMX-778899",
    operatorLicenseExpiresLabel: "18 de junio de 2027",
    dieselLiters: "400",
    dieselAmount: "8800",
    casetasAmount: "800",
    operatorQuota: "1200",
    clientCharge: "35000",
    paymentMethod: "transfer",
    requiresInvoice: true,
    hasClientBilling: true,
    attachedDocumentFileNames: ["Prog-SG-260524.pdf"],
  },
  {
    id: "WM-260526",
    maneuverCode: "WM-260526",
    origin: "Chihuahua",
    destination: "Hermosillo",
    clientName: "Walmart de México",
    clientId: "cli-walmart",
    unitId: "DEMO-TRC-009",
    operatorId: "op7",
    status: "scheduled",
    programmedAt: "2026-05-26T16:00:00Z",
    scheduledAt: "2026-05-28T10:00:00Z",
    operationType: "full",
    loadType: "vacio",
    containerType: "40hc",
    approximateWeightTons: "",
    equipment: ["DEMO-TRC-009-EQ1","DEMO-TRC-009-EQ2"],
    departureAt: null,
    arrivedAt: null,
    returnAt: null,
    creditDays: 45,
    hasIncident: false,
    routeDistanceKm: 315,
    maneuverKind: "Foránea",
    originPostalCode: "37000",
    originCityMunicipality: "Chihuahua, MX",
    destinationPostalCode: "20000",
    destinationCityMunicipality: "Hermosillo, MX",
    operatorLicenseNumber: "MTY-998877",
    operatorLicenseExpiresLabel: "1 de diciembre de 2026",
    dieselLiters: "450",
    dieselAmount: "9700",
    casetasAmount: "900",
    operatorQuota: "1300",
    clientCharge: "38500",
    paymentMethod: "transfer",
    requiresInvoice: true,
    hasClientBilling: true,
    attachedDocumentFileNames: ["Prog-WM-260526.pdf"],
  },
  {
    id: "CC-260505",
    maneuverCode: "CC-260505",
    origin: "Monterrey",
    destination: "Guadalajara",
    clientName: "Coca-Cola FEMSA",
    clientId: "cli-coca",
    unitId: "DEMO-TRC-010",
    operatorId: "op8",
    status: "completed",
    programmedAt: "2026-05-04T11:00:00Z",
    scheduledAt: "2026-05-04T13:00:00Z",
    operationType: "full",
    loadType: "vacio",
    containerType: "40ft",
    approximateWeightTons: "21",
    equipment: ["DEMO-TRC-010-EQ1","DEMO-TRC-010-EQ2"],
    departureAt: "2026-05-04T12:55:00Z",
    arrivedAt: "2026-05-05T18:20:00Z",
    returnAt: "2026-05-06T22:00:00Z",
    creditDays: 30,
    hasIncident: true,
    incidents: [
      {
        id: "inc-cc-delay",
        description:
          "Retraso en entrega por congestión y fila en andén de planta del cliente.",
        occurredAt: "2026-05-06T20:00:00Z",
        postedBy: "gvelasco",
              severity: "medium",
      },
    ],
    routeDistanceKm: 300,
    maneuverKind: "Local",
    originPostalCode: "50090",
    originCityMunicipality: "Monterrey, MX",
    destinationPostalCode: "62070",
    destinationCityMunicipality: "Guadalajara, MX",
    operatorLicenseNumber: "QRO-654321",
    operatorLicenseExpiresLabel: "20 de mayo de 2028",
    dieselLiters: "200",
    dieselAmount: "4500",
    casetasAmount: "400",
    operatorQuota: "800",
    clientCharge: "22000",
    paymentMethod: "cash",
    requiresInvoice: true,
    hasClientBilling: true,
    attachedDocumentFileNames: ["CP-CC-260505.pdf"],
  },
  {
    id: "PF-260507",
    maneuverCode: "PF-260507",
    origin: "Ciudad de México",
    destination: "Querétaro",
    clientName: "Peñoles",
    clientId: "cli-penoles",
    unitId: "DEMO-TRC-011",
    operatorId: "op9",
    status: "completed",
    programmedAt: "2026-05-06T11:00:00Z",
    scheduledAt: "2026-05-06T13:00:00Z",
    operationType: "plana",
    loadType: "lleno",
    containerType: "20ft",
    approximateWeightTons: "",
    equipment: ["DEMO-TRC-011-EQ1"],
    departureAt: "2026-05-06T12:55:00Z",
    arrivedAt: "2026-05-07T18:20:00Z",
    returnAt: "2026-05-08T22:00:00Z",
    creditDays: 30,
    hasIncident: true,
    incidents: [
      {
        id: "inc-pf-doc",
        description:
          "Carta porte con sello digital rechazado en punto de revisión; se reexpidió en patio.",
        occurredAt: "2026-05-07T14:30:00Z",
        postedBy: "gvelasco",
              severity: "medium",
      },
    ],
    routeDistanceKm: 312,
    maneuverKind: "Foránea",
    originPostalCode: "50090",
    originCityMunicipality: "Ciudad de México, MX",
    destinationPostalCode: "62070",
    destinationCityMunicipality: "Querétaro, MX",
    operatorLicenseNumber: "VER-887766",
    operatorLicenseExpiresLabel: "15 de enero de 2027",
    dieselLiters: "230",
    dieselAmount: "4900",
    casetasAmount: "450",
    operatorQuota: "880",
    clientCharge: "24000",
    paymentMethod: "transfer",
    requiresInvoice: false,
    hasClientBilling: true,
    attachedDocumentFileNames: ["CP-PF-260507.pdf"],
  },
  {
    id: "LV-260509",
    maneuverCode: "LV-260509",
    origin: "Tijuana",
    destination: "Mexicali",
    clientName: "Liverpool",
    clientId: "cli-liverpool",
    unitId: "DEMO-TRC-012",
    operatorId: "op6",
    status: "completed",
    programmedAt: "2026-05-08T11:00:00Z",
    scheduledAt: "2026-05-08T13:00:00Z",
    operationType: "sencillo",
    loadType: "vacio",
    containerType: "na",
    approximateWeightTons: "",
    equipment: ["DEMO-TRC-012-EQ1"],
    departureAt: "2026-05-08T12:55:00Z",
    arrivedAt: "2026-05-09T18:20:00Z",
    returnAt: "2026-05-10T22:00:00Z",
    creditDays: 30,
    hasIncident: false,
    routeDistanceKm: 324,
    maneuverKind: "Foránea",
    originPostalCode: "50090",
    originCityMunicipality: "Tijuana, MX",
    destinationPostalCode: "62070",
    destinationCityMunicipality: "Mexicali, MX",
    operatorLicenseNumber: "GDL-112233",
    operatorLicenseExpiresLabel: "10 de marzo de 2027",
    dieselLiters: "260",
    dieselAmount: "5300",
    casetasAmount: "500",
    operatorQuota: "960",
    clientCharge: "26000",
    paymentMethod: "transfer",
    requiresInvoice: true,
    hasClientBilling: true,
    attachedDocumentFileNames: ["CP-LV-260509.pdf"],
  },
  {
    id: "KC-260511",
    maneuverCode: "KC-260511",
    origin: "Puebla",
    destination: "Veracruz",
    clientName: "Kimberly-Clark",
    clientId: "cli-kc",
    unitId: "DEMO-TRC-013",
    operatorId: "op7",
    status: "completed",
    programmedAt: "2026-05-10T11:00:00Z",
    scheduledAt: "2026-05-10T13:00:00Z",
    operationType: "full",
    loadType: "lleno",
    containerType: "40ft",
    approximateWeightTons: "21",
    equipment: ["DEMO-TRC-013-EQ1","DEMO-TRC-013-EQ2"],
    departureAt: "2026-05-10T12:55:00Z",
    arrivedAt: "2026-05-11T18:20:00Z",
    returnAt: "2026-05-12T22:00:00Z",
    creditDays: 30,
    hasIncident: false,
    routeDistanceKm: 336,
    maneuverKind: "Foránea",
    originPostalCode: "50090",
    originCityMunicipality: "Puebla, MX",
    destinationPostalCode: "62070",
    destinationCityMunicipality: "Veracruz, MX",
    operatorLicenseNumber: "MTY-998877",
    operatorLicenseExpiresLabel: "1 de diciembre de 2026",
    dieselLiters: "290",
    dieselAmount: "5700",
    casetasAmount: "550",
    operatorQuota: "1040",
    clientCharge: "28000",
    paymentMethod: "cash",
    requiresInvoice: false,
    hasClientBilling: true,
    attachedDocumentFileNames: ["CP-KC-260511.pdf"],
  },
  {
    id: "FL-260513",
    maneuverCode: "FL-260513",
    origin: "Mérida",
    destination: "Cancún",
    clientName: "FEMSA Logística",
    clientId: "cli-femsa",
    unitId: "DEMO-TRC-014",
    operatorId: "op9",
    status: "completed",
    programmedAt: "2026-05-12T11:00:00Z",
    scheduledAt: "2026-05-12T13:00:00Z",
    operationType: "sencillo",
    loadType: "vacio",
    containerType: "na",
    approximateWeightTons: "",
    equipment: ["DEMO-TRC-014-EQ1"],
    departureAt: "2026-05-12T12:55:00Z",
    arrivedAt: "2026-05-13T18:20:00Z",
    returnAt: "2026-05-14T22:00:00Z",
    creditDays: 30,
    hasIncident: true,
    incidents: [
      {
        id: "inc-fl513-weather",
        description:
          "Cierre parcial de carretera por lluvia; reprogramación de ventana de entrega.",
        occurredAt: "2026-05-13T11:40:00Z",
        postedBy: "erios",
              severity: "high",
      },
    ],
    routeDistanceKm: 348,
    maneuverKind: "Local",
    originPostalCode: "50090",
    originCityMunicipality: "Mérida, MX",
    destinationPostalCode: "62070",
    destinationCityMunicipality: "Cancún, MX",
    operatorLicenseNumber: "VER-887766",
    operatorLicenseExpiresLabel: "15 de enero de 2027",
    dieselLiters: "320",
    dieselAmount: "6100",
    casetasAmount: "600",
    operatorQuota: "1120",
    clientCharge: "30000",
    paymentMethod: "transfer",
    requiresInvoice: true,
    hasClientBilling: true,
    attachedDocumentFileNames: ["CP-FL-260513.pdf"],
  },
  {
    id: "SR-260515",
    maneuverCode: "SR-260515",
    origin: "León",
    destination: "Aguascalientes",
    clientName: "Organización Soriana",
    clientId: "cli-soriana",
    unitId: "DEMO-TRC-015",
    operatorId: "op8",
    status: "completed",
    programmedAt: "2026-05-14T11:00:00Z",
    scheduledAt: "2026-05-14T13:00:00Z",
    operationType: "plana",
    loadType: "lleno",
    containerType: "20ft",
    approximateWeightTons: "",
    equipment: ["DEMO-TRC-015-EQ1"],
    departureAt: "2026-05-14T12:55:00Z",
    arrivedAt: "2026-05-15T18:20:00Z",
    returnAt: "2026-05-16T22:00:00Z",
    creditDays: 30,
    hasIncident: true,
    incidents: [
      {
        id: "inc-sr515-caseta",
        description:
          "Retención prolongada en caseta por falla del sistema TAG; pago en efectivo.",
        occurredAt: "2026-05-15T08:15:00Z",
        postedBy: "dcampos",
              severity: "medium",
      },
    ],
    routeDistanceKm: 360,
    maneuverKind: "Foránea",
    originPostalCode: "50090",
    originCityMunicipality: "León, MX",
    destinationPostalCode: "62070",
    destinationCityMunicipality: "Aguascalientes, MX",
    operatorLicenseNumber: "QRO-654321",
    operatorLicenseExpiresLabel: "20 de mayo de 2028",
    dieselLiters: "350",
    dieselAmount: "6500",
    casetasAmount: "650",
    operatorQuota: "1200",
    clientCharge: "32000",
    paymentMethod: "transfer",
    requiresInvoice: false,
    hasClientBilling: true,
    attachedDocumentFileNames: ["CP-SR-260515.pdf"],
  },
  {
    id: "WM-260517",
    maneuverCode: "WM-260517",
    origin: "Saltillo",
    destination: "Torreón",
    clientName: "Walmart de México",
    clientId: "cli-walmart",
    unitId: "DEMO-TRC-016",
    operatorId: "op6",
    status: "completed",
    programmedAt: "2026-05-16T11:00:00Z",
    scheduledAt: "2026-05-16T13:00:00Z",
    operationType: "full",
    loadType: "vacio",
    containerType: "40ft",
    approximateWeightTons: "21",
    equipment: ["DEMO-TRC-016-EQ1","DEMO-TRC-016-EQ2"],
    departureAt: "2026-05-16T12:55:00Z",
    arrivedAt: "2026-05-17T18:20:00Z",
    returnAt: "2026-05-18T22:00:00Z",
    creditDays: 30,
    hasIncident: true,
    incidents: [
      {
        id: "inc-wm517-tire",
        description:
          "Pinchazo en eje delantero; asistencia de grúa y cambio de llanta en ruta.",
        occurredAt: "2026-05-12T03:15:00Z",
        postedBy: "rvega",
              severity: "high",
      },
    ],
    routeDistanceKm: 372,
    maneuverKind: "Foránea",
    originPostalCode: "50090",
    originCityMunicipality: "Saltillo, MX",
    destinationPostalCode: "62070",
    destinationCityMunicipality: "Torreón, MX",
    operatorLicenseNumber: "GDL-112233",
    operatorLicenseExpiresLabel: "10 de marzo de 2027",
    dieselLiters: "380",
    dieselAmount: "6900",
    casetasAmount: "700",
    operatorQuota: "1280",
    clientCharge: "34000",
    paymentMethod: "cash",
    requiresInvoice: true,
    hasClientBilling: true,
    attachedDocumentFileNames: ["CP-WM-260517.pdf"],
  },
  {
    id: "BC-260519",
    maneuverCode: "BC-260519",
    origin: "Morelia",
    destination: "Colima",
    clientName: "Industrias Bachoco",
    clientId: "cli-bachoco",
    unitId: "DEMO-TRC-017",
    operatorId: "op7",
    status: "completed",
    programmedAt: "2026-05-18T11:00:00Z",
    scheduledAt: "2026-05-18T13:00:00Z",
    operationType: "plana",
    loadType: "lleno",
    containerType: "20ft",
    approximateWeightTons: "",
    equipment: ["DEMO-TRC-017-EQ1"],
    departureAt: "2026-05-18T12:55:00Z",
    arrivedAt: "2026-05-19T18:20:00Z",
    returnAt: "2026-05-20T22:00:00Z",
    creditDays: 30,
    hasIncident: true,
    incidents: [
      {
        id: "inc-bc519-client",
        description:
          "Cliente rechazó parcialmente la carga por diferencia en sellos; se documentó en bitácora.",
        occurredAt: "2026-05-19T16:45:00Z",
        postedBy: "gvelasco",
              severity: "low",
      },
    ],
    routeDistanceKm: 384,
    maneuverKind: "Foránea",
    originPostalCode: "50090",
    originCityMunicipality: "Morelia, MX",
    destinationPostalCode: "62070",
    destinationCityMunicipality: "Colima, MX",
    operatorLicenseNumber: "MTY-998877",
    operatorLicenseExpiresLabel: "1 de diciembre de 2026",
    dieselLiters: "410",
    dieselAmount: "7300",
    casetasAmount: "750",
    operatorQuota: "1360",
    clientCharge: "36000",
    paymentMethod: "transfer",
    requiresInvoice: false,
    hasClientBilling: true,
    attachedDocumentFileNames: ["CP-BC-260519.pdf"],
  },
  {
    id: "WM-260528",
    maneuverCode: "WM-260528",
    origin: "Chihuahua",
    destination: "Durango",
    clientName: "Walmart de México",
    clientId: "cli-walmart",
    unitId: "DEMO-TRC-018",
    operatorId: "op8",
    status: "cancelled",
    programmedAt: "2026-05-26T09:00:00Z",
    scheduledAt: "2026-05-27T06:00:00Z",
    operationType: "sencillo",
    loadType: "vacio",
    containerType: "na",
    approximateWeightTons: "",
    equipment: ["DEMO-TRC-018-EQ1"],
    departureAt: null,
    arrivedAt: null,
    returnAt: null,
    creditDays: 60,
    hasIncident: false,
    falseManeuver: false,
    cancellationNote: "Cliente suspendió la carga; unidad no salió de patio.",
    routeDistanceKm: 480,
    maneuverKind: "Foránea",
    originPostalCode: "31040",
    originCityMunicipality: "Chihuahua, CHIH",
    destinationPostalCode: "34000",
    destinationCityMunicipality: "Durango, DGO",
    operatorLicenseNumber: "QRO-654321",
    operatorLicenseExpiresLabel: "20 de mayo de 2028",
    hasClientBilling: true,
    attachedDocumentFileNames: ["Memo-cancelacion.pdf"],
  },
  {
    id: "SR-260529",
    maneuverCode: "SR-260529",
    origin: "Chihuahua",
    destination: "Durango",
    clientName: "Organización Soriana",
    clientId: "cli-soriana",
    unitId: "DEMO-TRC-019",
    operatorId: "op9",
    status: "cancelled",
    programmedAt: "2026-05-27T09:00:00Z",
    scheduledAt: "2026-05-28T06:00:00Z",
    operationType: "sencillo",
    loadType: "vacio",
    containerType: "na",
    approximateWeightTons: "",
    equipment: ["DEMO-TRC-019-EQ1"],
    departureAt: null,
    arrivedAt: null,
    returnAt: null,
    creditDays: 60,
    hasIncident: false,
    falseManeuver: false,
    cancellationNote: "Cliente suspendió la carga; unidad no salió de patio.",
    routeDistanceKm: 480,
    maneuverKind: "Foránea",
    originPostalCode: "31040",
    originCityMunicipality: "Chihuahua, CHIH",
    destinationPostalCode: "34000",
    destinationCityMunicipality: "Durango, DGO",
    operatorLicenseNumber: "VER-887766",
    operatorLicenseExpiresLabel: "15 de enero de 2027",
    hasClientBilling: true,
    attachedDocumentFileNames: ["Memo-cancelacion.pdf"],
  },
  {
    id: "LV-260530-A",
    maneuverCode: "LV-260530-A",
    origin: "Saltillo",
    destination: "Monclova",
    clientName: "Liverpool",
    clientId: "cli-liverpool",
    unitId: "DEMO-TRC-020",
    operatorId: "op6",
    status: "cancelled",
    programmedAt: "2026-05-29T10:30:00Z",
    scheduledAt: "2026-05-30T06:00:00Z",
    operationType: "full",
    loadType: "lleno",
    containerType: "40ft",
    approximateWeightTons: "18",
    equipment: ["DEMO-TRC-020-EQ1","DEMO-TRC-020-EQ2"],
    departureAt: null,
    arrivedAt: null,
    returnAt: null,
    creditDays: 45,
    hasIncident: false,
    falseManeuver: true,
    cancellationNote: "Maniobra en falso: se factura al cliente sin movimiento físico.",
    routeDistanceKm: 220,
    maneuverKind: "Foránea",
    originPostalCode: "25085",
    originCityMunicipality: "Saltillo, COAH",
    destinationPostalCode: "25700",
    destinationCityMunicipality: "Monclova, COAH",
    operatorLicenseNumber: "GDL-112233",
    operatorLicenseExpiresLabel: "10 de marzo de 2027",
    clientCharge: "42000",
    paymentMethod: "transfer",
    requiresInvoice: true,
    hasClientBilling: true,
    attachedDocumentFileNames: ["Acuerdo-en-falso.pdf"],
  },
  {
    id: "FL-260530-B",
    maneuverCode: "FL-260530-B",
    origin: "Monterrey",
    destination: "Saltillo",
    clientName: "FEMSA Logística",
    clientId: "cli-femsa",
    unitId: "DEMO-TRC-021",
    operatorId: "op7",
    status: "cancelled",
    programmedAt: "2026-05-29T11:30:00Z",
    scheduledAt: "2026-05-30T06:00:00Z",
    operationType: "full",
    loadType: "lleno",
    containerType: "40ft",
    approximateWeightTons: "18",
    equipment: ["DEMO-TRC-021-EQ1","DEMO-TRC-021-EQ2"],
    departureAt: null,
    arrivedAt: null,
    returnAt: null,
    creditDays: 45,
    hasIncident: false,
    falseManeuver: true,
    cancellationNote: "Maniobra en falso: se factura al cliente sin movimiento físico.",
    routeDistanceKm: 220,
    maneuverKind: "Foránea",
    originPostalCode: "25085",
    originCityMunicipality: "Monterrey, NL",
    destinationPostalCode: "25700",
    destinationCityMunicipality: "Saltillo, COAH",
    operatorLicenseNumber: "MTY-998877",
    operatorLicenseExpiresLabel: "1 de diciembre de 2026",
    clientCharge: "44000",
    paymentMethod: "transfer",
    requiresInvoice: true,
    hasClientBilling: true,
    attachedDocumentFileNames: ["Acuerdo-en-falso.pdf"],
  },
];
