import { Unit } from '@shared/models/logistics.models';

/** Tractores; estados coherentes con maniobras activas a finales de mayo 2026. */
export const SIM_DB_UNITS: Unit[] = [
  {
    id: "DEMO-TRC-001",
    plate: "01-TRC-MX",
    type: "Tractocamión 6x4",
    capacityKg: 40000,
    status: "in_use",
    serialNumber: "VIN-DEMO-001",
    name: "Tractor demo 1",
    trailerBrandAbbr: "INT",
    trailerYear: "2020",
    fleetMeta: {
      trailerBrandName: "International",
      trailerTenureMode: "owned",
      lastMaintenanceDate: "2026-04-15",
      verificationPhysMechDate: "2025-10-15",
      verificationPhysMechCost: 1750,
      verificationEmissionsDate: "2025-11-01",
      verificationEmissionsCost: 820,
      documentVerificationNames: ["verif-fisica-tracto.pdf", "verif-emisiones-tracto.pdf"],
      insurancePolicyNumber: "POL-DEMO-001",
      insuranceContractDate: "2025-01-10",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-002",
    plate: "02-TRC-MX",
    type: "Tractocamión 6x4",
    capacityKg: 40000,
    status: "in_use",
    serialNumber: "VIN-DEMO-002",
    name: "Tractor demo 2",
    trailerBrandAbbr: "KEN",
    trailerYear: "2021",
    fleetMeta: {
      trailerBrandName: "Kenworth",
      trailerTenureMode: "owned",
      lastMaintenanceDate: "2026-04-15",
      verificationPhysMechDate: "2025-10-15",
      verificationPhysMechCost: 1750,
      verificationEmissionsDate: "2025-11-01",
      verificationEmissionsCost: 820,
      documentVerificationNames: ["verif-fisica-tracto.pdf", "verif-emisiones-tracto.pdf"],
      insurancePolicyNumber: "POL-DEMO-002",
      insuranceContractDate: "2025-01-10",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-003",
    plate: "03-TRC-MX",
    type: "Tractocamión 6x4",
    capacityKg: 40000,
    status: "in_use",
    serialNumber: "VIN-DEMO-003",
    name: "Tractor demo 3",
    trailerBrandAbbr: "FRE",
    trailerYear: "2022",
    fleetMeta: {
      trailerBrandName: "Freightliner",
      trailerTenureMode: "leased",
      lastMaintenanceDate: "2026-04-15",
      verificationPhysMechDate: "2025-10-15",
      verificationPhysMechCost: 1750,
      verificationEmissionsDate: "2025-11-01",
      verificationEmissionsCost: 820,
      documentVerificationNames: ["verif-fisica-tracto.pdf", "verif-emisiones-tracto.pdf"],
      insurancePolicyNumber: "POL-DEMO-003",
      insuranceContractDate: "2025-01-10",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-004",
    plate: "04-TRC-MX",
    type: "Tractocamión 6x4",
    capacityKg: 40000,
    status: "in_use",
    serialNumber: "VIN-DEMO-004",
    name: "Tractor demo 4",
    trailerBrandAbbr: "VOL",
    trailerYear: "2023",
    fleetMeta: {
      trailerBrandName: "Volvo",
      trailerTenureMode: "owned",
      lastMaintenanceDate: "2026-04-15",
      verificationPhysMechDate: "2025-10-15",
      verificationPhysMechCost: 1750,
      verificationEmissionsDate: "2025-11-01",
      verificationEmissionsCost: 820,
      documentVerificationNames: ["verif-fisica-tracto.pdf", "verif-emisiones-tracto.pdf"],
      insurancePolicyNumber: "POL-DEMO-004",
      insuranceContractDate: "2025-01-10",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-005",
    plate: "05-TRC-MX",
    type: "Tractocamión 6x4",
    capacityKg: 40000,
    status: "in_use",
    serialNumber: "VIN-DEMO-005",
    name: "Tractor demo 5",
    trailerBrandAbbr: "PET",
    trailerYear: "2019",
    fleetMeta: {
      trailerBrandName: "Peterbilt",
      trailerTenureMode: "owned",
      lastMaintenanceDate: "2026-04-15",
      verificationPhysMechDate: "2025-10-15",
      verificationPhysMechCost: 1750,
      verificationEmissionsDate: "2025-11-01",
      verificationEmissionsCost: 820,
      documentVerificationNames: ["verif-fisica-tracto.pdf", "verif-emisiones-tracto.pdf"],
      insurancePolicyNumber: "POL-DEMO-005",
      insuranceContractDate: "2025-01-10",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-006",
    plate: "06-TRC-MX",
    type: "Tractocamión 6x4",
    capacityKg: 40000,
    status: "scheduled",
    serialNumber: "VIN-DEMO-006",
    name: "Tractor demo 6",
    trailerBrandAbbr: "INT",
    trailerYear: "2020",
    fleetMeta: {
      trailerBrandName: "International",
      trailerTenureMode: "leased",
      lastMaintenanceDate: "2026-04-15",
      verificationPhysMechDate: "2025-10-15",
      verificationPhysMechCost: 1750,
      verificationEmissionsDate: "2025-11-01",
      verificationEmissionsCost: 820,
      documentVerificationNames: ["verif-fisica-tracto.pdf", "verif-emisiones-tracto.pdf"],
      insurancePolicyNumber: "POL-DEMO-006",
      insuranceContractDate: "2025-01-10",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-007",
    plate: "07-TRC-MX",
    type: "Tractocamión 6x4",
    capacityKg: 40000,
    status: "scheduled",
    serialNumber: "VIN-DEMO-007",
    name: "Tractor demo 7",
    trailerBrandAbbr: "KEN",
    trailerYear: "2021",
    fleetMeta: {
      trailerBrandName: "Kenworth",
      trailerTenureMode: "owned",
      lastMaintenanceDate: "2026-04-15",
      verificationPhysMechDate: "2025-10-15",
      verificationPhysMechCost: 1750,
      verificationEmissionsDate: "2025-11-01",
      verificationEmissionsCost: 820,
      documentVerificationNames: ["verif-fisica-tracto.pdf", "verif-emisiones-tracto.pdf"],
      insurancePolicyNumber: "POL-DEMO-007",
      insuranceContractDate: "2025-01-10",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-008",
    plate: "08-TRC-MX",
    type: "Tractocamión 6x4",
    capacityKg: 40000,
    status: "scheduled",
    serialNumber: "VIN-DEMO-008",
    name: "Tractor demo 8",
    trailerBrandAbbr: "FRE",
    trailerYear: "2022",
    fleetMeta: {
      trailerBrandName: "Freightliner",
      trailerTenureMode: "owned",
      lastMaintenanceDate: "2026-04-15",
      verificationPhysMechDate: "2025-10-15",
      verificationPhysMechCost: 1750,
      verificationEmissionsDate: "2025-11-01",
      verificationEmissionsCost: 820,
      documentVerificationNames: ["verif-fisica-tracto.pdf", "verif-emisiones-tracto.pdf"],
      insurancePolicyNumber: "POL-DEMO-008",
      insuranceContractDate: "2025-01-10",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-009",
    plate: "09-TRC-MX",
    type: "Tractocamión 6x4",
    capacityKg: 40000,
    status: "scheduled",
    serialNumber: "VIN-DEMO-009",
    name: "Tractor demo 9",
    trailerBrandAbbr: "VOL",
    trailerYear: "2023",
    fleetMeta: {
      trailerBrandName: "Volvo",
      trailerTenureMode: "leased",
      lastMaintenanceDate: "2026-04-15",
      verificationPhysMechDate: "2025-10-15",
      verificationPhysMechCost: 1750,
      verificationEmissionsDate: "2025-11-01",
      verificationEmissionsCost: 820,
      documentVerificationNames: ["verif-fisica-tracto.pdf", "verif-emisiones-tracto.pdf"],
      insurancePolicyNumber: "POL-DEMO-009",
      insuranceContractDate: "2025-01-10",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-010",
    plate: "10-TRC-MX",
    type: "Tractocamión 6x4",
    capacityKg: 40000,
    status: "available",
    serialNumber: "VIN-DEMO-010",
    name: "Tractor demo 10",
    trailerBrandAbbr: "PET",
    trailerYear: "2019",
    fleetMeta: {
      trailerBrandName: "Peterbilt",
      trailerTenureMode: "owned",
      lastMaintenanceDate: "2026-04-15",
      verificationPhysMechDate: "2025-10-15",
      verificationPhysMechCost: 1750,
      verificationEmissionsDate: "2025-11-01",
      verificationEmissionsCost: 820,
      documentVerificationNames: ["verif-fisica-tracto.pdf", "verif-emisiones-tracto.pdf"],
      insurancePolicyNumber: "POL-DEMO-010",
      insuranceContractDate: "2025-01-10",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-011",
    plate: "11-TRC-MX",
    type: "Tractocamión 6x4",
    capacityKg: 40000,
    status: "available",
    serialNumber: "VIN-DEMO-011",
    name: "Tractor demo 11",
    trailerBrandAbbr: "INT",
    trailerYear: "2020",
    fleetMeta: {
      trailerBrandName: "International",
      trailerTenureMode: "owned",
      lastMaintenanceDate: "2026-04-15",
      verificationPhysMechDate: "2025-10-15",
      verificationPhysMechCost: 1750,
      verificationEmissionsDate: "2025-11-01",
      verificationEmissionsCost: 820,
      documentVerificationNames: ["verif-fisica-tracto.pdf", "verif-emisiones-tracto.pdf"],
      insurancePolicyNumber: "POL-DEMO-011",
      insuranceContractDate: "2025-01-10",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-012",
    plate: "12-TRC-MX",
    type: "Tractocamión 6x4",
    capacityKg: 40000,
    status: "available",
    serialNumber: "VIN-DEMO-012",
    name: "Tractor demo 12",
    trailerBrandAbbr: "KEN",
    trailerYear: "2021",
    fleetMeta: {
      trailerBrandName: "Kenworth",
      trailerTenureMode: "leased",
      lastMaintenanceDate: "2026-04-15",
      verificationPhysMechDate: "2025-10-15",
      verificationPhysMechCost: 1750,
      verificationEmissionsDate: "2025-11-01",
      verificationEmissionsCost: 820,
      documentVerificationNames: ["verif-fisica-tracto.pdf", "verif-emisiones-tracto.pdf"],
      insurancePolicyNumber: "POL-DEMO-012",
      insuranceContractDate: "2025-01-10",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-013",
    plate: "13-TRC-MX",
    type: "Tractocamión 6x4",
    capacityKg: 40000,
    status: "available",
    serialNumber: "VIN-DEMO-013",
    name: "Tractor demo 13",
    trailerBrandAbbr: "FRE",
    trailerYear: "2022",
    fleetMeta: {
      trailerBrandName: "Freightliner",
      trailerTenureMode: "owned",
      lastMaintenanceDate: "2026-04-15",
      verificationPhysMechDate: "2025-10-15",
      verificationPhysMechCost: 1750,
      verificationEmissionsDate: "2025-11-01",
      verificationEmissionsCost: 820,
      documentVerificationNames: ["verif-fisica-tracto.pdf", "verif-emisiones-tracto.pdf"],
      insurancePolicyNumber: "POL-DEMO-013",
      insuranceContractDate: "2025-01-10",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-014",
    plate: "14-TRC-MX",
    type: "Tractocamión 6x4",
    capacityKg: 40000,
    status: "available",
    serialNumber: "VIN-DEMO-014",
    name: "Tractor demo 14",
    trailerBrandAbbr: "VOL",
    trailerYear: "2023",
    fleetMeta: {
      trailerBrandName: "Volvo",
      trailerTenureMode: "owned",
      lastMaintenanceDate: "2026-04-15",
      verificationPhysMechDate: "2025-10-15",
      verificationPhysMechCost: 1750,
      verificationEmissionsDate: "2025-11-01",
      verificationEmissionsCost: 820,
      documentVerificationNames: ["verif-fisica-tracto.pdf", "verif-emisiones-tracto.pdf"],
      insurancePolicyNumber: "POL-DEMO-014",
      insuranceContractDate: "2025-01-10",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-015",
    plate: "15-TRC-MX",
    type: "Tractocamión 6x4",
    capacityKg: 40000,
    status: "available",
    serialNumber: "VIN-DEMO-015",
    name: "Tractor demo 15",
    trailerBrandAbbr: "PET",
    trailerYear: "2019",
    fleetMeta: {
      trailerBrandName: "Peterbilt",
      trailerTenureMode: "leased",
      lastMaintenanceDate: "2026-04-15",
      verificationPhysMechDate: "2025-10-15",
      verificationPhysMechCost: 1750,
      verificationEmissionsDate: "2025-11-01",
      verificationEmissionsCost: 820,
      documentVerificationNames: ["verif-fisica-tracto.pdf", "verif-emisiones-tracto.pdf"],
      insurancePolicyNumber: "POL-DEMO-015",
      insuranceContractDate: "2025-01-10",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-016",
    plate: "16-TRC-MX",
    type: "Tractocamión 6x4",
    capacityKg: 40000,
    status: "available",
    serialNumber: "VIN-DEMO-016",
    name: "Tractor demo 16",
    trailerBrandAbbr: "INT",
    trailerYear: "2020",
    fleetMeta: {
      trailerBrandName: "International",
      trailerTenureMode: "owned",
      lastMaintenanceDate: "2026-04-15",
      verificationPhysMechDate: "2025-10-15",
      verificationPhysMechCost: 1750,
      verificationEmissionsDate: "2025-11-01",
      verificationEmissionsCost: 820,
      documentVerificationNames: ["verif-fisica-tracto.pdf", "verif-emisiones-tracto.pdf"],
      insurancePolicyNumber: "POL-DEMO-016",
      insuranceContractDate: "2025-01-10",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-017",
    plate: "17-TRC-MX",
    type: "Tractocamión 6x4",
    capacityKg: 40000,
    status: "available",
    serialNumber: "VIN-DEMO-017",
    name: "Tractor demo 17",
    trailerBrandAbbr: "KEN",
    trailerYear: "2021",
    fleetMeta: {
      trailerBrandName: "Kenworth",
      trailerTenureMode: "owned",
      lastMaintenanceDate: "2026-04-15",
      verificationPhysMechDate: "2025-10-15",
      verificationPhysMechCost: 1750,
      verificationEmissionsDate: "2025-11-01",
      verificationEmissionsCost: 820,
      documentVerificationNames: ["verif-fisica-tracto.pdf", "verif-emisiones-tracto.pdf"],
      insurancePolicyNumber: "POL-DEMO-017",
      insuranceContractDate: "2025-01-10",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-018",
    plate: "18-TRC-MX",
    type: "Tractocamión 6x4",
    capacityKg: 40000,
    status: "available",
    serialNumber: "VIN-DEMO-018",
    name: "Tractor demo 18",
    trailerBrandAbbr: "FRE",
    trailerYear: "2022",
    fleetMeta: {
      trailerBrandName: "Freightliner",
      trailerTenureMode: "leased",
      lastMaintenanceDate: "2026-04-15",
      verificationPhysMechDate: "2025-10-15",
      verificationPhysMechCost: 1750,
      verificationEmissionsDate: "2025-11-01",
      verificationEmissionsCost: 820,
      documentVerificationNames: ["verif-fisica-tracto.pdf", "verif-emisiones-tracto.pdf"],
      insurancePolicyNumber: "POL-DEMO-018",
      insuranceContractDate: "2025-01-10",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-019",
    plate: "19-TRC-MX",
    type: "Tractocamión 6x4",
    capacityKg: 40000,
    status: "available",
    serialNumber: "VIN-DEMO-019",
    name: "Tractor demo 19",
    trailerBrandAbbr: "VOL",
    trailerYear: "2023",
    fleetMeta: {
      trailerBrandName: "Volvo",
      trailerTenureMode: "owned",
      lastMaintenanceDate: "2026-04-15",
      verificationPhysMechDate: "2025-10-15",
      verificationPhysMechCost: 1750,
      verificationEmissionsDate: "2025-11-01",
      verificationEmissionsCost: 820,
      documentVerificationNames: ["verif-fisica-tracto.pdf", "verif-emisiones-tracto.pdf"],
      insurancePolicyNumber: "POL-DEMO-019",
      insuranceContractDate: "2025-01-10",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-020",
    plate: "20-TRC-MX",
    type: "Tractocamión 6x4",
    capacityKg: 40000,
    status: "available",
    serialNumber: "VIN-DEMO-020",
    name: "Tractor demo 20",
    trailerBrandAbbr: "PET",
    trailerYear: "2019",
    fleetMeta: {
      trailerBrandName: "Peterbilt",
      trailerTenureMode: "owned",
      lastMaintenanceDate: "2026-04-15",
      verificationPhysMechDate: "2025-10-15",
      verificationPhysMechCost: 1750,
      verificationEmissionsDate: "2025-11-01",
      verificationEmissionsCost: 820,
      documentVerificationNames: ["verif-fisica-tracto.pdf", "verif-emisiones-tracto.pdf"],
      insurancePolicyNumber: "POL-DEMO-020",
      insuranceContractDate: "2025-01-10",
      insurancePaymentCadence: "annual"
    }
  },
  {
    id: "DEMO-TRC-021",
    plate: "21-TRC-MX",
    type: "Tractocamión 6x4",
    capacityKg: 40000,
    status: "available",
    serialNumber: "VIN-DEMO-021",
    name: "Tractor demo 21",
    trailerBrandAbbr: "INT",
    trailerYear: "2020",
    fleetMeta: {
      trailerBrandName: "International",
      trailerTenureMode: "leased",
      lastMaintenanceDate: "2026-04-15",
      verificationPhysMechDate: "2025-10-15",
      verificationPhysMechCost: 1750,
      verificationEmissionsDate: "2025-11-01",
      verificationEmissionsCost: 820,
      documentVerificationNames: ["verif-fisica-tracto.pdf", "verif-emisiones-tracto.pdf"],
      insurancePolicyNumber: "POL-DEMO-021",
      insuranceContractDate: "2025-01-10",
      insurancePaymentCadence: "annual"
    }
  },
];
